/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logicaDeNegocio.Proveedor;
import logicaDeNegocio.Sucursal;
import persistenciaJPA.exceptions.NonexistentEntityException;
import persistenciaJPA.exceptions.PreexistingEntityException;

/**
 *
 * @author Choni
 */
public class VentanaProveedor extends javax.swing.JInternalFrame {
    //CONTROLADORA DE LA INTERFAZ
    private ControladoraInterfaz miLogica;
    private DefaultTableModel modelo = new DefaultTableModel(){
        // sobreescribo el metodo para que no se modifiquen los campos de las filas en la tabla
        @Override
        public boolean isCellEditable(int rowIndex, int colIndex){
            return false;
        }
    };
    private DefaultComboBoxModel modeloComboBox = new DefaultComboBoxModel();
    private int banderaModificar;//bandera de modificacion
    
    /**
     * Creates new form VentanaProveedor
     */
    public VentanaProveedor(ControladoraInterfaz unaControladora) throws PreexistingEntityException {
        initComponents();
        this.miLogica = unaControladora;
        this.activarDatosProveedor(false);
        /// Agregar las cabeceras de la tabla
        this.modelo.addColumn("Id");
        this.modelo.addColumn("Razon social");
        this.modelo.addColumn("Correo electronico");
        this.modelo.addColumn("Direccion");
        this.modelo.addColumn("Localidad");
        this.modelo.addColumn("Telefono");
        this.modelo.addColumn("Pais");
        this.modelo.addColumn("CUIT");
        this.modelo.addColumn("Situacion tributaria");

        this.jTableProveedores.setModel(modelo);
        this.cargarTabla();    
        this.cargarComboBoxSucursales();
        this.banderaModificar = -1;
        // manejo de la ventana
        this.setClosable(true);
        this.setIconifiable(true);
        // busqueda
        this.jLabelSucursalBuscar.setEnabled(false);
        this.jComboBoxBuscarSucursal.setEnabled(false);
        this.jButtonBuscar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanelDatosDelProveedor = new javax.swing.JPanel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelRazonSocial = new javax.swing.JLabel();
        jTextFieldRazonSocial = new javax.swing.JTextField();
        jLabelCorreoElectronico = new javax.swing.JLabel();
        jTextFieldCorreoElectronico = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelLocalidad = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelPais = new javax.swing.JLabel();
        jLabelCUIT = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldLocalidad = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldPais = new javax.swing.JTextField();
        jTextFieldCUIT = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabelCamposObligatorios = new javax.swing.JLabel();
        jTextFieldSituacionTributaria = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabelSituacionTributaria = new javax.swing.JLabel();
        jLabelSucursal = new javax.swing.JLabel();
        jComboBoxSucursal = new javax.swing.JComboBox();
        jPanelListaDeProveedores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProveedores = new javax.swing.JTable();
        jButtonNuevoProveedor = new javax.swing.JButton();
        jButtonModificarProveedor = new javax.swing.JButton();
        jButtonEliminarProveedor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelSucursalBuscar = new javax.swing.JLabel();
        jComboBoxBuscarSucursal = new javax.swing.JComboBox();
        jButtonBuscar = new javax.swing.JButton();
        jCheckBoxBuscarPorSucursal = new javax.swing.JCheckBox();

        jPanelDatosDelProveedor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del proveedor"));

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelRazonSocial.setText("Razon social:");

        jLabelCorreoElectronico.setText("Correo electronico:");

        jLabelDireccion.setText("Direccion:");

        jLabelLocalidad.setText("Localidad:");

        jLabelTelefono.setText("Telefono:");

        jLabelPais.setText("Pais:");

        jLabelCUIT.setText("CUIT:");

        jLabel18.setText("*");

        jLabel19.setText("*");

        jLabel20.setText("*");

        jLabel21.setText("*");

        jLabel22.setText("*");

        jLabel23.setText("*");

        jLabel24.setText("*");

        jLabelCamposObligatorios.setForeground(java.awt.Color.red);
        jLabelCamposObligatorios.setText("( * ) Campos obligatorios");

        jLabel25.setText("*");

        jLabelSituacionTributaria.setText("Situacion tributaria:");

        jLabelSucursal.setText("Sucursal:");

        jComboBoxSucursal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelDatosDelProveedorLayout = new javax.swing.GroupLayout(jPanelDatosDelProveedor);
        jPanelDatosDelProveedor.setLayout(jPanelDatosDelProveedorLayout);
        jPanelDatosDelProveedorLayout.setHorizontalGroup(
            jPanelDatosDelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosDelProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosDelProveedorLayout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(jLabelCamposObligatorios)
                .addGap(116, 116, 116))
            .addGroup(jPanelDatosDelProveedorLayout.createSequentialGroup()
                .addGroup(jPanelDatosDelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosDelProveedorLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanelDatosDelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSucursal)
                            .addComponent(jLabelRazonSocial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosDelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldRazonSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jComboBoxSucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosDelProveedorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDatosDelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCorreoElectronico)
                            .addComponent(jLabelDireccion)
                            .addComponent(jLabelLocalidad)
                            .addComponent(jLabelTelefono)
                            .addComponent(jLabelPais)
                            .addComponent(jLabelCUIT)
                            .addComponent(jLabelSituacionTributaria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosDelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCUIT)
                            .addComponent(jTextFieldPais)
                            .addComponent(jTextFieldTelefono)
                            .addComponent(jTextFieldCorreoElectronico)
                            .addComponent(jTextFieldDireccion)
                            .addComponent(jTextFieldLocalidad)
                            .addComponent(jTextFieldSituacionTributaria, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosDelProveedorLayout.setVerticalGroup(
            jPanelDatosDelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosDelProveedorLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanelDatosDelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSucursal)
                    .addComponent(jComboBoxSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRazonSocial)
                    .addComponent(jTextFieldRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCorreoElectronico)
                    .addGroup(jPanelDatosDelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDatosDelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDireccion)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLocalidad)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefono)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPais)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCUIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCUIT)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSituacionTributaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabelSituacionTributaria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCamposObligatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        jPanelListaDeProveedores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Lista de proveedores"));

        jTableProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProveedores.setFocusable(false);
        jTableProveedores.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableProveedores);

        jButtonNuevoProveedor.setText("Nuevo");
        jButtonNuevoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoProveedorActionPerformed(evt);
            }
        });

        jButtonModificarProveedor.setText("Modificar");
        jButtonModificarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarProveedorActionPerformed(evt);
            }
        });

        jButtonEliminarProveedor.setText("Eliminar");
        jButtonEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarProveedorActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelSucursalBuscar.setText("Sucursal:");

        jComboBoxBuscarSucursal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jCheckBoxBuscarPorSucursal.setText("Buscar por Sucursal");
        jCheckBoxBuscarPorSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBuscarPorSucursalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabelSucursalBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBuscarSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBuscar)
                .addGap(88, 88, 88)
                .addComponent(jCheckBoxBuscarPorSucursal)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSucursalBuscar)
                    .addComponent(jComboBoxBuscarSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jCheckBoxBuscarPorSucursal))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelListaDeProveedoresLayout = new javax.swing.GroupLayout(jPanelListaDeProveedores);
        jPanelListaDeProveedores.setLayout(jPanelListaDeProveedoresLayout);
        jPanelListaDeProveedoresLayout.setHorizontalGroup(
            jPanelListaDeProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaDeProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaDeProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addGroup(jPanelListaDeProveedoresLayout.createSequentialGroup()
                        .addComponent(jButtonNuevoProveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModificarProveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEliminarProveedor))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelListaDeProveedoresLayout.setVerticalGroup(
            jPanelListaDeProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaDeProveedoresLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelListaDeProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevoProveedor)
                    .addComponent(jButtonModificarProveedor)
                    .addComponent(jButtonEliminarProveedor))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1027, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelDatosDelProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanelListaDeProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanelDatosDelProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelListaDeProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(24, Short.MAX_VALUE)))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoProveedorActionPerformed
        // TODO add your handling code here:
        activarDatosProveedor(true);
        
    }//GEN-LAST:event_jButtonNuevoProveedorActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        activarDatosProveedor(false);
        limpiar();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        if(this.banderaModificar == -1){
            crearProveedor();
        }
        else{
            this.modificarProveedor();
        }
        limpiar();
        activarDatosProveedor(false);
        try {
            actualizarFilas();
        } catch (PreexistingEntityException ex) {
            Logger.getLogger(VentanaProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarProveedorActionPerformed
        // TODO add your handling code here:
        int seleccionProveedor = this.jTableProveedores.getSelectedRow();
        int i = 1;
        if(seleccionProveedor == -1){// si no se selecciono nada de la tabla
            JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE UNA FILA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        else{
            i = JOptionPane.showConfirmDialog(this, "Estas Seguro ?", "Vas a Eliminar un proveedor", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                    int id = Integer.parseInt(this.jTableProveedores.getValueAt(seleccionProveedor, 0).toString());
                try {
                    miLogica.eliminarProveedor(id);
                    DefaultTableModel dtm = (DefaultTableModel) jTableProveedores.getModel();
                    dtm.removeRow(jTableProveedores.getSelectedRow()); 
                } catch (PreexistingEntityException ex) {
                    Logger.getLogger(VentanaProveedor.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(VentanaProveedor.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(VentanaProveedor.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                }
        }
    }//GEN-LAST:event_jButtonEliminarProveedorActionPerformed

    private void jButtonModificarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarProveedorActionPerformed
        // TODO add your handling code here:
        int seleccionProveedor = this.jTableProveedores.getSelectedRow();
        int i = 1;
        if(seleccionProveedor == -1){// si no se selecciono nada de la tabla
            JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE UNA FILA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        else{
            i = JOptionPane.showConfirmDialog(this, "Estas Seguro ?", "Vas a Modificar un proveedor", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                int id = Integer.parseInt(this.jTableProveedores.getValueAt(seleccionProveedor, 0).toString());
                try {
                    Proveedor unProveedor = miLogica.dameMiProveedor(id);
                    activarDatosProveedor(true);
                    this.jComboBoxSucursal.setEnabled(false);// desabilito la opcion de elegir la sucursal
                    this.jTextFieldRazonSocial.setText(unProveedor.getRazonSocial());
                    this.jTextFieldCorreoElectronico.setText(unProveedor.getCorreoElectronico());
                    this.jTextFieldDireccion.setText(unProveedor.getDireccion());
                    this.jTextFieldLocalidad.setText(unProveedor.getLocalidad());
                    this.jTextFieldTelefono.setText(unProveedor.getTelefono());
                    this.jTextFieldPais.setText(unProveedor.getPais());
                    this.jTextFieldCUIT.setText(unProveedor.getCuit());
                    this.jTextFieldSituacionTributaria.setText(unProveedor.getSituacionTributaria());
                    this.banderaModificar = unProveedor.getId();
                } catch (PreexistingEntityException ex) {
                    Logger.getLogger(VentanaProveedor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButtonModificarProveedorActionPerformed

    private void jCheckBoxBuscarPorSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBuscarPorSucursalActionPerformed
        if(this.jCheckBoxBuscarPorSucursal.isSelected()){
            this.jLabelSucursalBuscar.setEnabled(true);
            this.jComboBoxBuscarSucursal.setEnabled(true);
            this.jButtonBuscar.setEnabled(true);
        }
        else{
            this.jLabelSucursalBuscar.setEnabled(false);
            this.jComboBoxBuscarSucursal.setEnabled(false);
            this.jButtonBuscar.setEnabled(false);
            this.jComboBoxBuscarSucursal.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jCheckBoxBuscarPorSucursalActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        int numeroSucursal = Integer.parseInt(this.jComboBoxBuscarSucursal.getSelectedItem().toString());
        List<Sucursal> misSucursales = new LinkedList<Sucursal>();
        List<Proveedor> misProveedores = new LinkedList<Proveedor>();
        try {
            misSucursales = this.miLogica.dameSucursales();
        } catch (PreexistingEntityException ex) {
            Logger.getLogger(VentanaArticulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        Sucursal unaSucursal = null;
        for(Sucursal e : misSucursales){
            if(e.isSucursal(numeroSucursal)){
                unaSucursal = e;
            }
        }
        misProveedores = unaSucursal.getProveedores();// saco todos los articulos de la sucursal
        if(misProveedores.isEmpty()){// si la lista esta vacia
            JOptionPane.showMessageDialog(null, "NO EXISTEN PROVEEDORES EN ESTA SUCURSAL", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        else{// si mi lista no esta vacia
            // limpio mi tabla de articulos
            DefaultTableModel modelo = (DefaultTableModel) jTableProveedores.getModel();
            int filas = jTableProveedores.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
            // cargo mi tabla con la nueva lista de tiques
            Object[]fila= new Object[9];
            for(Proveedor e : misProveedores){
                fila[0] = e.getId();
                fila[1] = e.getRazonSocial();
                fila[2] = e.getCorreoElectronico();
                fila[3] = e.getDireccion();
                fila[4] = e.getLocalidad();
                fila[5] = e.getTelefono();
                fila[6] = e.getPais();
                fila[7] = e.getCuit();
                fila[8] = e.getSituacionTributaria();
                this.modelo.addRow(fila);
                this.jTableProveedores.setModel(modelo);
            }
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminarProveedor;
    private javax.swing.JButton jButtonModificarProveedor;
    private javax.swing.JButton jButtonNuevoProveedor;
    private javax.swing.JCheckBox jCheckBoxBuscarPorSucursal;
    private javax.swing.JComboBox jComboBoxBuscarSucursal;
    private javax.swing.JComboBox jComboBoxSucursal;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabelCUIT;
    private javax.swing.JLabel jLabelCamposObligatorios;
    private javax.swing.JLabel jLabelCorreoElectronico;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelLocalidad;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JLabel jLabelRazonSocial;
    private javax.swing.JLabel jLabelSituacionTributaria;
    private javax.swing.JLabel jLabelSucursal;
    private javax.swing.JLabel jLabelSucursalBuscar;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDatosDelProveedor;
    private javax.swing.JPanel jPanelListaDeProveedores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProveedores;
    private javax.swing.JTextField jTextFieldCUIT;
    private javax.swing.JTextField jTextFieldCorreoElectronico;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldLocalidad;
    private javax.swing.JTextField jTextFieldPais;
    private javax.swing.JTextField jTextFieldRazonSocial;
    private javax.swing.JTextField jTextFieldSituacionTributaria;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
    
    /// Metodos
    public void activarDatosProveedor(boolean b){
        this.jLabel18.setEnabled(b);
        this.jLabel19.setEnabled(b);
        this.jLabel20.setEnabled(b);
        this.jLabel21.setEnabled(b);
        this.jLabel22.setEnabled(b);
        this.jLabel23.setEnabled(b);
        this.jLabel24.setEnabled(b);
        this.jLabel25.setEnabled(b);
        this.jComboBoxSucursal.setEnabled(b);
        this.jButtonAceptar.setEnabled(b);
        this.jButtonCancelar.setEnabled(b);
        this.jLabelSucursal.setEnabled(b);
        this.jLabelRazonSocial.setEnabled(b);
        this.jLabelCorreoElectronico.setEnabled(b);
        this.jLabelDireccion.setEnabled(b);
        this.jLabelLocalidad.setEnabled(b);
        this.jLabelTelefono.setEnabled(b);
        this.jLabelPais.setEnabled(b);
        this.jLabelCUIT.setEnabled(b);
        this.jLabelSituacionTributaria.setEnabled(b);
        this.jTextFieldRazonSocial.setEnabled(b);
        this.jTextFieldCorreoElectronico.setEnabled(b);
        this.jTextFieldDireccion.setEnabled(b);
        this.jTextFieldLocalidad.setEnabled(b);
        this.jTextFieldTelefono.setEnabled(b);
        this.jTextFieldPais.setEnabled(b);
        this.jTextFieldCUIT.setEnabled(b);
        this.jTextFieldSituacionTributaria.setEnabled(b);
        this.jLabelCamposObligatorios.setEnabled(b);
    }
    
    private void limpiar(){
        this.jTextFieldRazonSocial.setText("");
        this.jTextFieldCorreoElectronico.setText("");
        this.jTextFieldDireccion.setText("");
        this.jTextFieldLocalidad.setText("");
        this.jTextFieldTelefono.setText("");
        this.jTextFieldPais.setText("");
        this.jTextFieldCUIT.setText("");
        this.jTextFieldSituacionTributaria.setText("");
        this.jComboBoxSucursal.setSelectedIndex(0);
    }
    
    public void cargarTabla() throws PreexistingEntityException{
        List<Proveedor> proveedores = this.miLogica.dameProveedores();
        Object[]fila= new Object[9];
        for(Proveedor e:proveedores){
            fila[0] = e.getId();
            fila[1] = e.getRazonSocial();
            fila[2] = e.getCorreoElectronico();
            fila[3] = e.getDireccion();
            fila[4] = e.getLocalidad();
            fila[5] = e.getTelefono();
            fila[6] = e.getPais();
            fila[7] = e.getCuit();
            fila[8] = e.getSituacionTributaria();
            this.modelo.addRow(fila);
            this.jTableProveedores.setModel(modelo);
        }   
    }
    
    public void cargarComboBoxSucursales() throws PreexistingEntityException{
        List<Sucursal> sucursales = this.miLogica.dameSucursales();
        for(Sucursal e : sucursales){
            this.modeloComboBox.addElement(e.getNumeroSucursal());
        }
        this.jComboBoxSucursal.setModel(modeloComboBox);// cargo al combo box para agregar articulo
        this.jComboBoxBuscarSucursal.setModel(modeloComboBox);// cargo al combobox para buscar mi articulo por sucursal
    }
    
    public void actualizarFilas() throws PreexistingEntityException{
        DefaultTableModel modelo = (DefaultTableModel) jTableProveedores.getModel();
        int filas = jTableProveedores.getRowCount();
        for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
        }
        cargarTabla();
    }
    
    public void crearProveedor(){
        String razonSocial = this.jTextFieldRazonSocial.getText();
        String correoElectronico = this.jTextFieldCorreoElectronico.getText();
        String direccion = this.jTextFieldDireccion.getText();
        String localidad = this.jTextFieldLocalidad.getText();
        String telefono = this.jTextFieldTelefono.getText();
        String pais = this.jTextFieldPais.getText();
        String cuit = this.jTextFieldCUIT.getText();
        String situacionTributaria = this.jTextFieldSituacionTributaria.getText();
        try {
            this.miLogica.crearProveedor(razonSocial, correoElectronico, direccion, localidad, telefono, pais, cuit, situacionTributaria);
        } catch (Exception ex) {
            Logger.getLogger(VentanaProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void modificarProveedor(){
        String razonSocial = this.jTextFieldRazonSocial.getText();
        String correoElectronico = this.jTextFieldCorreoElectronico.getText();
        String direccion = this.jTextFieldDireccion.getText();
        String localidad = this.jTextFieldLocalidad.getText();
        String telefono = this.jTextFieldTelefono.getText();
        String pais = this.jTextFieldPais.getText();
        String cuit = this.jTextFieldCUIT.getText();
        String situacionTributaria = this.jTextFieldSituacionTributaria.getText();
        try {
            this.miLogica.modificarProveedor(this.banderaModificar, razonSocial, correoElectronico, direccion, localidad, telefono, pais, cuit, situacionTributaria);
            this.banderaModificar = -1;
        } catch (Exception ex) {
            Logger.getLogger(VentanaProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
