/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logicaDeNegocio.Cuota;
import logicaDeNegocio.Proyecto;
import persistenciaJPA.exceptions.NonexistentEntityException;
import persistenciaJPA.exceptions.PreexistingEntityException;

/**
 *
 * @author FamiliaGomez
 */
public class VentanaCuota extends javax.swing.JInternalFrame {
    //CONTROLADORA DE LA INTERFAZ
    private ControladoraInterfaz miLogica;
    private DefaultTableModel modeloEquipo = new DefaultTableModel(){
        // sobreescribo el metodo para que no se modifiquen los campos de las filas en la tabla
        @Override
        public boolean isCellEditable(int rowIndex, int colIndex){
            return false;
        }
    };
    private int banderaModificar;//bandera de modificacion
    private Proyecto unProyecto = null;
    /**
     * Creates new form VentanaCuota
     */
    public VentanaCuota(ControladoraInterfaz unaControladoraInterfaz) throws PreexistingEntityException {
        initComponents();
        this.miLogica = unaControladoraInterfaz;
        banderaModificar = -1;
        // manejo de la ventana
        this.setClosable(true);
        this.setIconifiable(true);
        /// Agregar las cabeceras de la tabla
        modeloEquipo.addColumn("Id Cuota");
        modeloEquipo.addColumn("Monto");
        modeloEquipo.addColumn("Tipo de Cuota");
        modeloEquipo.addColumn("Id Proyecto");
        modeloEquipo.addColumn("Nombre Encargado");
        modeloEquipo.addColumn("Apellido Encargado");
        this.jTableCuotas.setModel(modeloEquipo);
        
        this.activarDatosProyecto(false);
        this.activarDatosCuota(false);
        this.jButtonBuscar.setEnabled(false);
        this.jButtonAceptar.setEnabled(false);
        this.jButtonCancelar.setEnabled(false);
        this.cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDatosProyecto = new javax.swing.JPanel();
        jLabelIdProyecto = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldIdProyecto = new javax.swing.JTextField();
        jTextFieldNombreEncargado = new javax.swing.JTextField();
        jTextFieldApellidoEncargado = new javax.swing.JTextField();
        jLabelNombreEncargado = new javax.swing.JLabel();
        jLabelApellidoEncargado = new javax.swing.JLabel();
        jLabelFechaInicio = new javax.swing.JLabel();
        jTextFieldFechaInicio = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCuotas = new javax.swing.JTable();
        jButtonNuevo = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jPanelDatosCuota = new javax.swing.JPanel();
        jLabelIdCuota = new javax.swing.JLabel();
        jLabelMonto = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jTextFieldIdCuota = new javax.swing.JTextField();
        jTextFieldMonto = new javax.swing.JTextField();
        jTextFieldTipo = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        jPanelDatosProyecto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del Proyecto"));

        jLabelIdProyecto.setText("Id:");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jTextFieldNombreEncargado.setEditable(false);

        jTextFieldApellidoEncargado.setEditable(false);

        jLabelNombreEncargado.setText("Nombre Encargado:");

        jLabelApellidoEncargado.setText("Apellido Encargado:");

        jLabelFechaInicio.setText("Fecha Inicio:");

        jTextFieldFechaInicio.setEditable(false);

        javax.swing.GroupLayout jPanelDatosProyectoLayout = new javax.swing.GroupLayout(jPanelDatosProyecto);
        jPanelDatosProyecto.setLayout(jPanelDatosProyectoLayout);
        jPanelDatosProyectoLayout.setHorizontalGroup(
            jPanelDatosProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelIdProyecto)
                        .addComponent(jLabelNombreEncargado))
                    .addComponent(jLabelApellidoEncargado)
                    .addComponent(jLabelFechaInicio, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosProyectoLayout.createSequentialGroup()
                        .addGroup(jPanelDatosProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIdProyecto)
                            .addComponent(jTextFieldNombreEncargado)
                            .addComponent(jTextFieldApellidoEncargado, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar))
                    .addComponent(jTextFieldFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosProyectoLayout.setVerticalGroup(
            jPanelDatosProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdProyecto)
                    .addComponent(jButtonBuscar)
                    .addComponent(jTextFieldIdProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreEncargado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldApellidoEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelApellidoEncargado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaInicio)
                    .addComponent(jTextFieldFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cuotas"));

        jTableCuotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCuotas);

        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEliminar)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevo)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonEliminar))
                .addContainerGap())
        );

        jPanelDatosCuota.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos de Cuota"));

        jLabelIdCuota.setText("Id Cuota:");

        jLabelMonto.setText("Monto Cuota: $");

        jLabelTipo.setText("Tipo de Cuota:");

        jTextFieldIdCuota.setEditable(false);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosCuotaLayout = new javax.swing.GroupLayout(jPanelDatosCuota);
        jPanelDatosCuota.setLayout(jPanelDatosCuotaLayout);
        jPanelDatosCuotaLayout.setHorizontalGroup(
            jPanelDatosCuotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosCuotaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 89, Short.MAX_VALUE))
            .addGroup(jPanelDatosCuotaLayout.createSequentialGroup()
                .addGroup(jPanelDatosCuotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosCuotaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelDatosCuotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelDatosCuotaLayout.createSequentialGroup()
                                .addComponent(jLabelMonto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatosCuotaLayout.createSequentialGroup()
                                .addComponent(jLabelIdCuota)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIdCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelDatosCuotaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)))
                .addContainerGap())
        );
        jPanelDatosCuotaLayout.setVerticalGroup(
            jPanelDatosCuotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosCuotaLayout.createSequentialGroup()
                .addGroup(jPanelDatosCuotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdCuota)
                    .addComponent(jTextFieldIdCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosCuotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMonto)
                    .addComponent(jTextFieldMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosCuotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipo)
                    .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanelDatosCuotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDatosProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDatosCuota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelDatosProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelDatosCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        // TODO add your handling code here:
        this.activarDatosProyecto(true);
        this.jButtonCancelar.setEnabled(true);
        this.jButtonBuscar.setEnabled(true);
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
         if(this.jTextFieldIdProyecto.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "INGRESE UN CODIGO PARA REALIZAR LA BUSQUEDA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);JOptionPane.showMessageDialog(null, "INGRESE UN CODIGO PARA REALIZAR LA BUSQUEDA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
         else{
             List<Proyecto> proyectos = null;
            int idProyecto = Integer.parseInt(this.jTextFieldIdProyecto.getText());// leo y guardo el id de un proyecto
            try {
                proyectos = this.miLogica.dameProyectos();
            } catch (PreexistingEntityException ex) {
                Logger.getLogger(VentanaTurno.class.getName()).log(Level.SEVERE, null, ex);
            }
            for(Proyecto e : proyectos){// recorro la lista de proyectos
                if(e.isId(idProyecto)){// si corresponde al id lo almaceno en unProyecto
                    this.unProyecto = e;
                }
            }
            if(this.unProyecto != null){// verifico si encontro al proyecto
                this.jTextFieldNombreEncargado.setText(this.unProyecto.getUnEncargado().getNombre());// muestro el nombre del encargado
                this.jTextFieldApellidoEncargado.setText(this.unProyecto.getUnEncargado().getApellido());// muestro el apellido del encargado
                this.activarDatosProyecto(false);
                this.activarDatosCuota(true);
                this.jButtonBuscar.setEnabled(false);
                this.jButtonAceptar.setEnabled(true);
                this.jButtonCancelar.setEnabled(true);
            }
            else{// si no encuentro a un cliente con el idProyecto
                JOptionPane.showMessageDialog(null, "NO EXISTE UN PROYECTO CON EL ID: "+idProyecto, "ERROR", JOptionPane.ERROR_MESSAGE);
            }
         }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        if(this.banderaModificar == -1){
            this.crearCuota();
        }
        else{
            this.modificarCuota();
        }
        this.activarDatosProyecto(false);
        this.activarDatosCuota(false);
        this.jButtonBuscar.setEnabled(false);
        this.jButtonAceptar.setEnabled(false);
        this.jButtonCancelar.setEnabled(false);
        this.limpiarDatos();
        try {       
            this.actualizarFilas();
        } catch (PreexistingEntityException ex) {
            Logger.getLogger(VentanaArticulo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.activarDatosProyecto(false);
        this.activarDatosCuota(false);
        this.jButtonBuscar.setEnabled(false);
        this.jButtonAceptar.setEnabled(false);
        this.jButtonCancelar.setEnabled(false);
        this.limpiarDatos();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        int seleccionCuota = this.jTableCuotas.getSelectedRow();
        int i = 1;
        if(seleccionCuota == -1){// si no se selecciono nada de la tabla
            JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE UNA FILA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        else{
            i = JOptionPane.showConfirmDialog(this, "Estas Seguro ?", "Vas a Modificar una Cuota", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                int idCuota = Integer.parseInt(this.jTableCuotas.getValueAt(seleccionCuota, 0).toString());
                int idProyecto = Integer.parseInt(this.jTableCuotas.getValueAt(seleccionCuota, 3).toString());
                try {
                    Proyecto unProyecto = this.miLogica.dameMiProyecto(idProyecto);
                    for(Cuota e : unProyecto.getCuotas()){// recorro la lista de cuotas de un proyecto
                        if(e.isCuota(idCuota)){
                            // datos del proyecto
                            this.jTextFieldIdProyecto.setText(String.valueOf(unProyecto.getId()));
                            this.jTextFieldNombreEncargado.setText(unProyecto.getUnEncargado().getNombre());
                            this.jTextFieldApellidoEncargado.setText(unProyecto.getUnEncargado().getApellido());
                            // datos de la cuota
                            this.jTextFieldIdCuota.setText(String.valueOf(e.getId()));
                            this.jTextFieldMonto.setText(String.valueOf(e.getMonto()));
                            this.jTextFieldTipo.setText(e.getTipoDeCuota());
                            // activacion de datos
                            this.activarDatosProyecto(false);
                            this.activarDatosCuota(true);
                            this.jButtonBuscar.setEnabled(false);
                            this.jButtonAceptar.setEnabled(true);
                            this.jButtonCancelar.setEnabled(true);
                            this.banderaModificar = e.getId();// toma un numero mayor a cero
                        }
                    }
                } catch (PreexistingEntityException ex) {
                    Logger.getLogger(VentanaEquipo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        int seleccionCuota = this.jTableCuotas.getSelectedRow();
        int i = 1;
        if(seleccionCuota == -1){// si no se selecciono nada de la tabla
            JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE UNA FILA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        else{
            i = JOptionPane.showConfirmDialog(this, "Estas Seguro ?", "Vas a Modificar una Cuota", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                int idCuota = Integer.parseInt(this.jTableCuotas.getValueAt(seleccionCuota, 0).toString());
                int idProyecto = Integer.parseInt(this.jTableCuotas.getValueAt(seleccionCuota, 3).toString());
                try {
                    this.miLogica.eliminarCuota(idCuota, idProyecto);
                    this.actualizarFilas();
                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(VentanaEquipo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(VentanaEquipo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JLabel jLabelApellidoEncargado;
    private javax.swing.JLabel jLabelFechaInicio;
    private javax.swing.JLabel jLabelIdCuota;
    private javax.swing.JLabel jLabelIdProyecto;
    private javax.swing.JLabel jLabelMonto;
    private javax.swing.JLabel jLabelNombreEncargado;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelDatosCuota;
    private javax.swing.JPanel jPanelDatosProyecto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCuotas;
    private javax.swing.JTextField jTextFieldApellidoEncargado;
    private javax.swing.JTextField jTextFieldFechaInicio;
    private javax.swing.JTextField jTextFieldIdCuota;
    private javax.swing.JTextField jTextFieldIdProyecto;
    private javax.swing.JTextField jTextFieldMonto;
    private javax.swing.JTextField jTextFieldNombreEncargado;
    private javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables

    public void activarDatosProyecto(boolean b){
        this.jPanelDatosProyecto.setEnabled(b);
        this.jLabelIdProyecto.setEnabled(b);
        this.jLabelNombreEncargado.setEnabled(b);
        this.jLabelApellidoEncargado.setEnabled(b);
        this.jLabelFechaInicio.setEnabled(b);
        this.jTextFieldIdProyecto.setEnabled(b);
        this.jTextFieldIdProyecto.setEnabled(b);
        this.jTextFieldNombreEncargado.setEnabled(b);
        this.jTextFieldApellidoEncargado.setEnabled(b);
        this.jTextFieldFechaInicio.setEnabled(b);
    }
    
    public void activarDatosCuota(boolean b){
        this.jPanelDatosCuota.setEnabled(b);
        this.jLabelIdCuota.setEnabled(b);
        this.jLabelMonto.setEnabled(b);
        this.jLabelTipo.setEnabled(b);
        this.jTextFieldIdCuota.setEnabled(b);
        this.jTextFieldMonto.setEnabled(b);
        this.jTextFieldTipo.setEnabled(b);
    }
    
    public void limpiarDatos(){
        this.jTextFieldIdProyecto.setText("");
        this.jTextFieldNombreEncargado.setText("");
        this.jTextFieldApellidoEncargado.setText("");
        this.jTextFieldFechaInicio.setText("");
        this.jTextFieldIdCuota.setText("");
        this.jTextFieldMonto.setText("");
        this.jTextFieldTipo.setText("");
        // limpiar variables locales
        this.unProyecto = null;
    }
    
    public void cargarTabla() throws PreexistingEntityException{
        List<Cuota> cuotas = this.miLogica.dameCuotas();
        List<Proyecto> proyectos = this.miLogica.dameProyectos();
        Object[]fila= new Object[6];
        for(Proyecto e : proyectos){
                for(Cuota eq : e.getCuotas()){
                    fila[0] = eq.getId();
                    fila[1] = eq.getMonto();
                    fila[2] = eq.getTipoDeCuota();
                    fila[3] = e.getId();
                    fila[4] = e.getUnEncargado().getNombre();
                    fila[4] = e.getUnEncargado().getApellido();
                    this.modeloEquipo.addRow(fila);
                    this.jTableCuotas.setModel(modeloEquipo);
                }
            }
    }
    
     public void actualizarFilas() throws PreexistingEntityException{
        DefaultTableModel modelo = (DefaultTableModel) jTableCuotas.getModel();
        int filas = jTableCuotas.getRowCount();
        for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
        }
        cargarTabla();
    }
     
     public void crearCuota(){
        double montoCuota = Double.valueOf(this.jTextFieldMonto.getText());
        String tipoCuota = this.jTextFieldTipo.getText();
        try {
            this.miLogica.crearCuota(this.unProyecto.getId(), montoCuota, tipoCuota);
        } catch (Exception ex) {
            Logger.getLogger(VentanaEquipo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
    public void modificarCuota(){
        int idCuota = Integer.parseInt(this.jTextFieldIdCuota.getText());
        int idProyecto = Integer.parseInt(this.jTextFieldIdProyecto.getText());
        double montoCuota = Double.valueOf(this.jTextFieldMonto.getText());
        String tipoCuota = this.jTextFieldTipo.getText();
        try {
            this.miLogica.modificarCuota(idCuota, idProyecto, montoCuota, tipoCuota);
            this.banderaModificar = -1;
        } catch (Exception ex) {
            Logger.getLogger(VentanaEquipo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}
