/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logicaDeNegocio.Articulo;
import logicaDeNegocio.Sucursal;
import persistenciaJPA.exceptions.NonexistentEntityException;
import persistenciaJPA.exceptions.PreexistingEntityException;

/**
 *
 * @author Choni
 */
public class VentanaArticulo extends javax.swing.JInternalFrame {
    //CONTROLADORA DE LA INTERFAZ
    private ControladoraInterfaz miLogica;
    private DefaultTableModel modelo = new DefaultTableModel(){
        // sobreescribo el metodo para que no se modifiquen los campos de las filas en la tabla
        @Override
        public boolean isCellEditable(int rowIndex, int colIndex){
            return false;
        }
    };
    private DefaultComboBoxModel modeloComboBox = new DefaultComboBoxModel();
    private int banderaModificar;//bandera de modificacion
    /**
     * Creates new form VentanaTique
     */
    public VentanaArticulo(ControladoraInterfaz unaControladora) throws PreexistingEntityException {
        initComponents();
        this.miLogica = unaControladora;
        this.activarDatosArticulos(false);
        /// Agregar las cabeceras de la tabla
        this.modelo.addColumn("Id");
        this.modelo.addColumn("Nombre");
        this.modelo.addColumn("Precio costo");
        this.modelo.addColumn("Precio venta");
        this.modelo.addColumn("Descuento mayorista");
        this.modelo.addColumn("Cantidad real");
        this.modelo.addColumn("Cantidad minima");
        this.modelo.addColumn("Descripcion");
        this.modelo.addColumn("Codigo de barra");
        this.jTableArticulos.setModel(modelo);
        this.cargarTabla();
        this.cargarComboBoxSucursales();
        banderaModificar = -1;
        // manejo de la ventana
        this.setClosable(true);
        this.setIconifiable(true);
        // busqueda de articulos
        this.jLabelSucursalBuscar.setEnabled(false);
        this.jComboBoxSucursalBuscar.setSelectedIndex(0);
        this.jComboBoxSucursalBuscar.setEnabled(false);
        this.jButtonBuscarSucursal.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListaArticulo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableArticulos = new javax.swing.JTable();
        jButtonNuevoArticulo = new javax.swing.JButton();
        jButtonModificarArticulo = new javax.swing.JButton();
        jButtonEliminarArticulo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxArticulosSucursal = new javax.swing.JCheckBox();
        jButtonBuscarSucursal = new javax.swing.JButton();
        jComboBoxSucursalBuscar = new javax.swing.JComboBox();
        jLabelSucursalBuscar = new javax.swing.JLabel();
        jPanelDatosArticulo1 = new javax.swing.JPanel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabelNombreArticulo = new javax.swing.JLabel();
        jLabelPrecioVenta = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelDescuentoMayorista = new javax.swing.JLabel();
        jLabelPrecioCosto = new javax.swing.JLabel();
        jLabelCodigoBarra = new javax.swing.JLabel();
        jTextFieldPrecioVenta = new javax.swing.JTextField();
        jTextFieldPrecioCosto = new javax.swing.JTextField();
        jTextFieldCodigoBarra = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jSpinnerDescuento = new javax.swing.JSpinner();
        jLabelNombreArticulo1 = new javax.swing.JLabel();
        jLabelNombreArticulo2 = new javax.swing.JLabel();
        jLabelNombreArticulo3 = new javax.swing.JLabel();
        jLabelNombreArticulo4 = new javax.swing.JLabel();
        jLabelNombreArticulo5 = new javax.swing.JLabel();
        jLabelNombreArticulo8 = new javax.swing.JLabel();
        jLabelIdArticulo = new javax.swing.JLabel();
        jTextFieldIdArticulo = new javax.swing.JTextField();
        jCheckBoxCodigoBarra = new javax.swing.JCheckBox();
        jLabelSucursal = new javax.swing.JLabel();
        jComboBoxSucursal = new javax.swing.JComboBox();
        jPanelStockArticulo = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelCantidadReal = new javax.swing.JLabel();
        jLabelCantidadMin = new javax.swing.JLabel();
        jTextFieldCantidadMin = new javax.swing.JTextField();
        jTextFieldCantidadReal = new javax.swing.JTextField();
        jLabelNombreArticulo6 = new javax.swing.JLabel();
        jLabelNombreArticulo7 = new javax.swing.JLabel();
        jLabelIdStock = new javax.swing.JLabel();
        jTextFieldIdStock = new javax.swing.JTextField();

        jPanelListaArticulo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Lista de articulos"));

        jTableArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableArticulos.setFocusable(false);
        jTableArticulos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableArticulos);

        jButtonNuevoArticulo.setText("Nuevo");
        jButtonNuevoArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoArticuloActionPerformed(evt);
            }
        });

        jButtonModificarArticulo.setText("Modificar");
        jButtonModificarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarArticuloActionPerformed(evt);
            }
        });

        jButtonEliminarArticulo.setText("Eliminar");
        jButtonEliminarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarArticuloActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jCheckBoxArticulosSucursal.setText("Busqueda por sucursal");
        jCheckBoxArticulosSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxArticulosSucursalActionPerformed(evt);
            }
        });

        jButtonBuscarSucursal.setText("Buscar");
        jButtonBuscarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarSucursalActionPerformed(evt);
            }
        });

        jComboBoxSucursalBuscar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelSucursalBuscar.setText("Sucursal:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSucursalBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSucursalBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(jButtonBuscarSucursal)
                .addGap(73, 73, 73)
                .addComponent(jCheckBoxArticulosSucursal)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSucursalBuscar)
                    .addComponent(jComboBoxSucursalBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarSucursal)
                    .addComponent(jCheckBoxArticulosSucursal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelListaArticuloLayout = new javax.swing.GroupLayout(jPanelListaArticulo);
        jPanelListaArticulo.setLayout(jPanelListaArticuloLayout);
        jPanelListaArticuloLayout.setHorizontalGroup(
            jPanelListaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaArticuloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addGroup(jPanelListaArticuloLayout.createSequentialGroup()
                        .addComponent(jButtonNuevoArticulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModificarArticulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEliminarArticulo)))
                .addContainerGap())
        );
        jPanelListaArticuloLayout.setVerticalGroup(
            jPanelListaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaArticuloLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelListaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevoArticulo)
                    .addComponent(jButtonModificarArticulo)
                    .addComponent(jButtonEliminarArticulo))
                .addContainerGap())
        );

        jPanelDatosArticulo1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del articulo"));

        jLabel20.setForeground(java.awt.Color.red);
        jLabel20.setText("( * ) Campos obligatorios");

        jLabelNombreArticulo.setText("Nombre:");

        jLabelPrecioVenta.setText("Precio venta: $");

        jLabelDescripcion.setText("Descripcion:");

        jLabelDescuentoMayorista.setText("Descuento mayorista:");

        jLabelPrecioCosto.setText("Precio costo: $");

        jLabelCodigoBarra.setText("Codigo de barra: ");

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDescripcion);

        jSpinnerDescuento.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(0.1f)));
        jSpinnerDescuento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelNombreArticulo1.setText("%");

        jLabelNombreArticulo2.setText("*");

        jLabelNombreArticulo3.setText("*");

        jLabelNombreArticulo4.setText("*");

        jLabelNombreArticulo5.setText("*");

        jLabelNombreArticulo8.setText("*");

        jLabelIdArticulo.setText("Id Articulo:");

        jTextFieldIdArticulo.setEditable(false);

        jCheckBoxCodigoBarra.setText("S/N");
        jCheckBoxCodigoBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCodigoBarraActionPerformed(evt);
            }
        });

        jLabelSucursal.setText("Sucursal:");

        jComboBoxSucursal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sucursal 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelDatosArticulo1Layout = new javax.swing.GroupLayout(jPanelDatosArticulo1);
        jPanelDatosArticulo1.setLayout(jPanelDatosArticulo1Layout);
        jPanelDatosArticulo1Layout.setHorizontalGroup(
            jPanelDatosArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosArticulo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSucursal)
                    .addComponent(jLabelIdArticulo)
                    .addGroup(jPanelDatosArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelDescuentoMayorista)
                        .addComponent(jLabelPrecioVenta, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelPrecioCosto, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelCodigoBarra, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelNombreArticulo, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosArticulo1Layout.createSequentialGroup()
                        .addComponent(jTextFieldPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNombreArticulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelDatosArticulo1Layout.createSequentialGroup()
                        .addGroup(jPanelDatosArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(jPanelDatosArticulo1Layout.createSequentialGroup()
                                .addComponent(jSpinnerDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNombreArticulo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNombreArticulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatosArticulo1Layout.createSequentialGroup()
                                .addComponent(jTextFieldPrecioCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNombreArticulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatosArticulo1Layout.createSequentialGroup()
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNombreArticulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatosArticulo1Layout.createSequentialGroup()
                                .addGroup(jPanelDatosArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelDatosArticulo1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBoxCodigoBarra))
                                    .addComponent(jScrollPane2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNombreArticulo8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatosArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBoxSucursal, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldIdArticulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                        .addGap(0, 8, Short.MAX_VALUE))))
        );
        jPanelDatosArticulo1Layout.setVerticalGroup(
            jPanelDatosArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosArticulo1Layout.createSequentialGroup()
                .addGroup(jPanelDatosArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdArticulo)
                    .addComponent(jTextFieldIdArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSucursal)
                    .addComponent(jComboBoxSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelDatosArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreArticulo)
                    .addComponent(jLabelNombreArticulo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecioCosto)
                    .addComponent(jTextFieldPrecioCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreArticulo3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecioVenta)
                    .addComponent(jTextFieldPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreArticulo4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescuentoMayorista)
                    .addComponent(jLabelNombreArticulo5)
                    .addComponent(jSpinnerDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreArticulo1))
                .addGroup(jPanelDatosArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosArticulo1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombreArticulo8)
                            .addComponent(jCheckBoxCodigoBarra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosArticulo1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelDatosArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCodigoBarra)
                            .addComponent(jTextFieldCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanelDatosArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescripcion)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addContainerGap())
        );

        jPanelStockArticulo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del stock del articulo"));

        jLabel21.setForeground(java.awt.Color.red);
        jLabel21.setText("( * ) Campos obligatorios");

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelCantidadReal.setText("Cantidad real:");

        jLabelCantidadMin.setText("Cantidad minima:");

        jTextFieldCantidadMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadMinActionPerformed(evt);
            }
        });

        jTextFieldCantidadReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadRealActionPerformed(evt);
            }
        });

        jLabelNombreArticulo6.setText("*");

        jLabelNombreArticulo7.setText("*");

        jLabelIdStock.setText("Id Stock:");

        jTextFieldIdStock.setEditable(false);

        javax.swing.GroupLayout jPanelStockArticuloLayout = new javax.swing.GroupLayout(jPanelStockArticulo);
        jPanelStockArticulo.setLayout(jPanelStockArticuloLayout);
        jPanelStockArticuloLayout.setHorizontalGroup(
            jPanelStockArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStockArticuloLayout.createSequentialGroup()
                .addGroup(jPanelStockArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStockArticuloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAceptar))
                    .addGroup(jPanelStockArticuloLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanelStockArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelIdStock)
                            .addComponent(jLabelCantidadReal)
                            .addComponent(jLabelCantidadMin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelStockArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCantidadMin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIdStock, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCantidadReal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelStockArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStockArticuloLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)
                        .addContainerGap())
                    .addGroup(jPanelStockArticuloLayout.createSequentialGroup()
                        .addGroup(jPanelStockArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombreArticulo6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombreArticulo7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanelStockArticuloLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelStockArticuloLayout.setVerticalGroup(
            jPanelStockArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStockArticuloLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelStockArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdStock)
                    .addComponent(jTextFieldIdStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelStockArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCantidadReal)
                    .addComponent(jTextFieldCantidadReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreArticulo6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelStockArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCantidadMin)
                    .addComponent(jTextFieldCantidadMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreArticulo7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelStockArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDatosArticulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelStockArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelListaArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelListaArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelDatosArticulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelStockArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCantidadMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadMinActionPerformed

    private void jTextFieldCantidadRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadRealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadRealActionPerformed

    private void jButtonNuevoArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoArticuloActionPerformed
        this.activarDatosArticulos(true);
        this.limpiarDatosArticulos();
    }//GEN-LAST:event_jButtonNuevoArticuloActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.activarDatosArticulos(false);
        this.limpiarDatosArticulos();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        if(this.banderaModificar == -1){
            this.crearArticulo();
        }
        else{
            this.modificarArticulo();
        }
        this.activarDatosArticulos(false);
        this.limpiarDatosArticulos();
        try {       
            actualizarFilas();
        } catch (PreexistingEntityException ex) {
            Logger.getLogger(VentanaArticulo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonModificarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarArticuloActionPerformed
        // TODO add your handling code here:
        int seleccionArticulo = this.jTableArticulos.getSelectedRow();
        int i = 1;
        if(seleccionArticulo == -1){// si no se selecciono nada de la tabla
            JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE UNA FILA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        else{
            i = JOptionPane.showConfirmDialog(this, "Estas Seguro ?", "Vas a Modificar un Articulo", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                int id = Integer.parseInt(this.jTableArticulos.getValueAt(seleccionArticulo, 0).toString());
                try {
                    Articulo unArticulo = miLogica.dameMiArticulo(id);
                    this.activarDatosArticulos(true);
                    this.jComboBoxSucursal.setEnabled(false);// desabilito la sucursal para modificar
                    this.jTextFieldIdArticulo.setText(String.valueOf(unArticulo.getId()));
                    this.jTextFieldNombre.setText(unArticulo.getNombre());
                    this.jTextFieldPrecioCosto.setText(String.valueOf(unArticulo.getPrecioCosto()));
                    this.jTextFieldPrecioVenta.setText(String.valueOf(unArticulo.getPrecioVenta()));
                    this.jSpinnerDescuento.setValue(unArticulo.getDescuentoMayorista());
                    if(unArticulo.getCodigoBarra().equalsIgnoreCase("Sin Codigo de Barra")){
                        this.jTextFieldCodigoBarra.setText("Sin Codigo de Barra");
                        this.jCheckBoxCodigoBarra.setSelected(true);
                        this.jTextFieldCodigoBarra.setEnabled(false);
                    }
                    else{
                        this.jTextFieldCodigoBarra.setText(unArticulo.getCodigoBarra());
                        this.jCheckBoxCodigoBarra.setSelected(false);
                    }
                    this.jTextAreaDescripcion.setText(unArticulo.getDescripcion());
                    this.jTextFieldIdStock.setText(String.valueOf(unArticulo.getStock().getId()));
                    this.jTextFieldCantidadReal.setText(String.valueOf(unArticulo.getStock().getCantidadReal()));
                    this.jTextFieldCantidadMin.setText(String.valueOf(unArticulo.getStock().getCantidadMinima()));
                    this.banderaModificar = unArticulo.getId();
                } catch (PreexistingEntityException ex) {
                    Logger.getLogger(VentanaProveedor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButtonModificarArticuloActionPerformed

    private void jCheckBoxCodigoBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCodigoBarraActionPerformed
        // TODO add your handling code here:
        if (this.jCheckBoxCodigoBarra.isSelected()) {
            this.jTextFieldCodigoBarra.setText("Sin Codigo de Barra");
            this.jTextFieldCodigoBarra.setEnabled(false);
        } else {
            this.jTextFieldCodigoBarra.setEnabled(true);
            this.jTextFieldCodigoBarra.setText("");
        }
    }//GEN-LAST:event_jCheckBoxCodigoBarraActionPerformed

    private void jButtonEliminarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarArticuloActionPerformed
        // TODO add your handling code here:
        int seleccionArticulo = this.jTableArticulos.getSelectedRow();
        int i = 1;
        if(seleccionArticulo == -1){// si no se selecciono nada de la tabla
            JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE UNA FILA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        else{
            i = JOptionPane.showConfirmDialog(this, "Estas Seguro ?", "Vas a Eliminar un articulo", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                int id = Integer.parseInt(this.jTableArticulos.getValueAt(seleccionArticulo, 0).toString());
                try {
                    miLogica.eliminarArticulo(id);
                    DefaultTableModel dtm = (DefaultTableModel) jTableArticulos.getModel();
                    dtm.removeRow(jTableArticulos.getSelectedRow()); 
                } catch (PreexistingEntityException ex) {
                    Logger.getLogger(VentanaProveedor.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(VentanaProveedor.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(VentanaProveedor.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        }
    }//GEN-LAST:event_jButtonEliminarArticuloActionPerformed

    private void jCheckBoxArticulosSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxArticulosSucursalActionPerformed
        // TODO add your handling code here:
        if(this.jCheckBoxArticulosSucursal.isSelected()){
            this.jLabelSucursalBuscar.setEnabled(true);
            this.jComboBoxSucursalBuscar.setSelectedIndex(0);
            this.jComboBoxSucursalBuscar.setEnabled(true);
            this.jButtonBuscarSucursal.setEnabled(true);
        }
        else{
            this.jLabelSucursalBuscar.setEnabled(false);
            this.jComboBoxSucursalBuscar.setEnabled(false);
            this.jButtonBuscarSucursal.setEnabled(false);
            // limpio todos los articulos de mi tabla
            DefaultTableModel modelo = (DefaultTableModel) jTableArticulos.getModel();
            int filas = jTableArticulos.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
            try {
                this.cargarTabla();// cargo todos los articulos a mi tabla
            } catch (PreexistingEntityException ex) {
                Logger.getLogger(VentanaArticulo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jCheckBoxArticulosSucursalActionPerformed

    private void jButtonBuscarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarSucursalActionPerformed
        int numeroSucursal = Integer.parseInt(this.jComboBoxSucursalBuscar.getSelectedItem().toString());
        List<Sucursal> misSucursales = new LinkedList<Sucursal>();
        List<Articulo> misArticulos = new LinkedList<Articulo>();
        try {
            misSucursales = this.miLogica.dameSucursales();
        } catch (PreexistingEntityException ex) {
            Logger.getLogger(VentanaArticulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        Sucursal unaSucursal = null;
        for(Sucursal e : misSucursales){
            if(e.isSucursal(numeroSucursal)){
                unaSucursal = e;
            }
        }
        misArticulos = unaSucursal.getArticulos();// saco todos los articulos de la sucursal
        if(misArticulos.isEmpty()){// si la lista esta vacia
            JOptionPane.showMessageDialog(null, "NO EXISTEN ARTICULOS EN ESTA SUCURSAL", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        else{// si mi lista no esta vacia
            // limpio mi tabla de articulos
            DefaultTableModel modelo = (DefaultTableModel) jTableArticulos.getModel();
            int filas = jTableArticulos.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
            // cargo mi tabla con la nueva lista de tiques
            Object[]fila= new Object[9];
            for(Articulo e : misArticulos){
                fila[0] = e.getId();
                fila[1] = e.getNombre();
                fila[2] = e.getPrecioCosto();
                fila[3] = e.getPrecioVenta();
                fila[4] = e.getDescuentoMayorista();
                fila[5] = e.getStock().getCantidadReal();
                fila[6] = e.getStock().getCantidadMinima();
                fila[7] = e.getDescripcion();
                fila[8] = e.getCodigoBarra();
                this.modelo.addRow(fila);
                this.jTableArticulos.setModel(modelo);
            }
        }
    }//GEN-LAST:event_jButtonBuscarSucursalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonBuscarSucursal;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminarArticulo;
    private javax.swing.JButton jButtonModificarArticulo;
    private javax.swing.JButton jButtonNuevoArticulo;
    private javax.swing.JCheckBox jCheckBoxArticulosSucursal;
    private javax.swing.JCheckBox jCheckBoxCodigoBarra;
    private javax.swing.JComboBox jComboBoxSucursal;
    private javax.swing.JComboBox jComboBoxSucursalBuscar;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabelCantidadMin;
    private javax.swing.JLabel jLabelCantidadReal;
    private javax.swing.JLabel jLabelCodigoBarra;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelDescuentoMayorista;
    private javax.swing.JLabel jLabelIdArticulo;
    private javax.swing.JLabel jLabelIdStock;
    private javax.swing.JLabel jLabelNombreArticulo;
    private javax.swing.JLabel jLabelNombreArticulo1;
    private javax.swing.JLabel jLabelNombreArticulo2;
    private javax.swing.JLabel jLabelNombreArticulo3;
    private javax.swing.JLabel jLabelNombreArticulo4;
    private javax.swing.JLabel jLabelNombreArticulo5;
    private javax.swing.JLabel jLabelNombreArticulo6;
    private javax.swing.JLabel jLabelNombreArticulo7;
    private javax.swing.JLabel jLabelNombreArticulo8;
    private javax.swing.JLabel jLabelPrecioCosto;
    private javax.swing.JLabel jLabelPrecioVenta;
    private javax.swing.JLabel jLabelSucursal;
    private javax.swing.JLabel jLabelSucursalBuscar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDatosArticulo1;
    private javax.swing.JPanel jPanelListaArticulo;
    private javax.swing.JPanel jPanelStockArticulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerDescuento;
    private javax.swing.JTable jTableArticulos;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextField jTextFieldCantidadMin;
    private javax.swing.JTextField jTextFieldCantidadReal;
    private javax.swing.JTextField jTextFieldCodigoBarra;
    private javax.swing.JTextField jTextFieldIdArticulo;
    private javax.swing.JTextField jTextFieldIdStock;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecioCosto;
    private javax.swing.JTextField jTextFieldPrecioVenta;
    // End of variables declaration//GEN-END:variables

    public void activarDatosArticulos(Boolean b){
        this.jLabelSucursal.setEnabled(b);
        this.jComboBoxSucursal.setEnabled(b);
        this.jLabelNombreArticulo.setEnabled(b);
        this.jLabelPrecioCosto.setEnabled(b);
        this.jLabelPrecioVenta.setEnabled(b);
        this.jLabelDescuentoMayorista.setEnabled(b);
        this.jLabelCodigoBarra.setEnabled(b);
        this.jLabelDescripcion.setEnabled(b);
        this.jLabelCantidadMin.setEnabled(b);
        this.jLabelCantidadReal.setEnabled(b);
        this.jLabel20.setEnabled(b);
        this.jLabel21.setEnabled(b);
        this.jLabelNombreArticulo1.setEnabled(b);
        this.jLabelNombreArticulo2.setEnabled(b);
        this.jLabelNombreArticulo3.setEnabled(b);
        this.jLabelNombreArticulo4.setEnabled(b);
        this.jLabelNombreArticulo5.setEnabled(b);
        this.jLabelNombreArticulo6.setEnabled(b);
        this.jLabelNombreArticulo7.setEnabled(b);
        this.jLabelNombreArticulo8.setEnabled(b);
        this.jTextFieldNombre.setEnabled(b);
        this.jTextFieldPrecioCosto.setEnabled(b);
        this.jTextFieldPrecioVenta.setEnabled(b);
        this.jSpinnerDescuento.setEnabled(b);
        this.jTextFieldCodigoBarra.setEnabled(b);
        this.jTextFieldCantidadReal.setEnabled(b);
        this.jTextFieldCantidadMin.setEnabled(b);
        this.jTextAreaDescripcion.setEnabled(b);
        this.jButtonAceptar.setEnabled(b);
        this.jButtonCancelar.setEnabled(b);
        this.jLabelIdStock.setEnabled(b);
        this.jLabelIdArticulo.setEnabled(b);
        this.jScrollPane2.setEnabled(b);
        this.jCheckBoxCodigoBarra.setEnabled(b);
    }

    public void limpiarDatosArticulos(){
        this.jTextFieldNombre.setText("");
        this.jTextFieldPrecioCosto.setText("");
        this.jTextFieldPrecioVenta.setText("");
        this.jSpinnerDescuento.setValue(0);
        this.jTextFieldCodigoBarra.setText("");
        this.jTextAreaDescripcion.setText("");
        this.jTextFieldCantidadMin.setText("");
        this.jTextFieldCantidadReal.setText("");
        this.jTextFieldIdArticulo.setText("");
        this.jTextFieldIdStock.setText("");
        this.jCheckBoxCodigoBarra.setSelected(false);
        this.jComboBoxSucursal.setSelectedIndex(0);
    }
    
    public void cargarTabla() throws PreexistingEntityException{
        List<Articulo> articulos = this.miLogica.dameArticulos();
        Object[]fila= new Object[9];
        for(Articulo e:articulos){
            fila[0] = e.getId();
            fila[1] = e.getNombre();
            fila[2] = e.getPrecioCosto();
            fila[3] = e.getPrecioVenta();
            fila[4] = e.getDescuentoMayorista();
            fila[5] = e.getStock().getCantidadReal();
            fila[6] = e.getStock().getCantidadMinima();
            fila[7] = e.getDescripcion();
            fila[8] = e.getCodigoBarra();
            this.modelo.addRow(fila);
            this.jTableArticulos.setModel(modelo);
        }        
    }
    
    public void cargarComboBoxSucursales() throws PreexistingEntityException{
        List<Sucursal> sucursales = this.miLogica.dameSucursales();
        for(Sucursal e : sucursales){
            this.modeloComboBox.addElement(e.getNumeroSucursal());
        }
        this.jComboBoxSucursal.setModel(modeloComboBox);// cargo al combo box para agregar articulo
        this.jComboBoxSucursalBuscar.setModel(modeloComboBox);// cargo al combobox para buscar mi articulo por sucursal
    }
    
    public void crearArticulo(){
        String nombre = this.jTextFieldNombre.getText();
        float precioCosto = Float.parseFloat(this.jTextFieldPrecioCosto.getText());
        float precioVenta = Float.parseFloat(this.jTextFieldPrecioVenta.getText());
        float descuentoMayorista = Float.parseFloat(this.jSpinnerDescuento.getValue().toString());
        int cantidadMin = Integer.parseInt(this.jTextFieldCantidadMin.getText().toString());
        int cantidadReal = Integer.parseInt(this.jTextFieldCantidadReal.getText().toString());
        int numeroSucursal = Integer.parseInt(this.jComboBoxSucursal.getSelectedItem().toString());
        String descripcion = this.jTextAreaDescripcion.getText();
        String codigoBarra = this.jTextFieldCodigoBarra.getText();
        try {
            this.miLogica.crearArticulo(nombre, descripcion, codigoBarra, precioCosto, precioVenta, descuentoMayorista, cantidadReal, cantidadMin, numeroSucursal);
        } catch (Exception ex) {
            Logger.getLogger(VentanaArticulo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void modificarArticulo(){
        String nombre = this.jTextFieldNombre.getText();
        float precioCosto = Float.parseFloat(this.jTextFieldPrecioCosto.getText());
        float precioVenta = Float.parseFloat(this.jTextFieldPrecioVenta.getText());
        float descuentoMayorista = Float.parseFloat(this.jSpinnerDescuento.getValue().toString());
        int cantidadMin = Integer.parseInt(this.jTextFieldCantidadMin.getText());
        int cantidadReal = Integer.parseInt(this.jTextFieldCantidadReal.getText());
        String descripcion = this.jTextAreaDescripcion.getText();
        String codigoBarra = this.jTextFieldCodigoBarra.getText();
        int idArticulo = Integer.parseInt(this.jTextFieldIdArticulo.getText());
        int idStock = Integer.parseInt(this.jTextFieldIdStock.getText()); 
        try {
            this.miLogica.modificarArticulo(idArticulo, nombre, descripcion, codigoBarra, precioCosto, precioVenta, descuentoMayorista, idStock, cantidadReal, cantidadMin);
            this.banderaModificar = -1;
        } catch (Exception ex) {
            Logger.getLogger(VentanaArticulo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void actualizarFilas() throws PreexistingEntityException{
        DefaultTableModel modelo = (DefaultTableModel) jTableArticulos.getModel();
        int filas = jTableArticulos.getRowCount();
        for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
        }
        cargarTabla();
    }
}
