/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logicaDeNegocio.Articulo;
import logicaDeNegocio.Cliente;
import logicaDeNegocio.Empleado;
import logicaDeNegocio.Equipo;
import logicaDeNegocio.Sucursal;
import persistenciaJPA.exceptions.PreexistingEntityException;

/**
 *
 * @author Choni
 */
public class VentanaTurno extends javax.swing.JInternalFrame {
    //CONTROLADORA DE LA INTERFAZ
    ControladoraInterfaz miLogica;
    private DefaultTableModel modeloTurnos = new DefaultTableModel(){
        // sobreescribo el metodo para que no se modifiquen los campos de las filas en la tabla
        @Override
        public boolean isCellEditable(int rowIndex, int colIndex){
            return false;
        }
    };
    private DefaultTableModel modeloDetallesTurno = new DefaultTableModel(){
        // sobreescribo el metodo para que no se modifiquen los campos de las filas en la tabla
        @Override
        public boolean isCellEditable(int rowIndex, int colIndex){
            return false;
        }
    };
    private DefaultComboBoxModel modeloComboBoxSucursal = new DefaultComboBoxModel();
    private DefaultComboBoxModel modeloComboBoxTipoTurno = new DefaultComboBoxModel();
    private DefaultComboBoxModel modeloComboBoxIdEquipo = new DefaultComboBoxModel();
    private Cliente unCliente = null;
    private Empleado unEmpleado = null;
    private Articulo unArticulo = null;
    // lista de id de articulos para el detalle
    private List<Integer> idArticulos = null;// si contiene -1 es porque es un envio a tercero
    private List<Integer> cantidades = null;// contiene las cantidades para los detalles del turno
    private List<String> descipcionDetalle = null;// descripcion de cada detalle
    private List<String> nombres = null;
    private List<Float> precios = null;
    
    /**
     * Creates new form VentanaTurno
     */
    public VentanaTurno(ControladoraInterfaz unaControladora) throws PreexistingEntityException {
        initComponents();
        this.miLogica = unaControladora;
        this.setClosable(true);// boton para cerrar
        this.setIconifiable(true);// boton para minimizar
        // Cabecera de la tabla turnos
        modeloTurnos.addColumn("Id");
        modeloTurnos.addColumn("Fecha");
        modeloTurnos.addColumn("Hora");
        modeloTurnos.addColumn("Cliente");
        modeloTurnos.addColumn("Numero de Sucursal");
        modeloTurnos.addColumn("Finalizado");
        this.jTableTurnos.setModel(modeloTurnos);
        
        this.idArticulos = new LinkedList<Integer>();
        this.cantidades = new LinkedList<Integer>();
        this.descipcionDetalle = new LinkedList<String>();
        this.nombres = new LinkedList<String>();
        this.precios = new LinkedList<Float>();
        
        this.activarTodosLosDatosTurno(false);
        this.cargarComboBoxTipoTurno();
        this.cargarComboBoxSucursal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTurnos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButtonNuevo = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelIdTurno = new javax.swing.JLabel();
        jTextFieldIdTurno = new javax.swing.JTextField();
        jLabelNumeroSucursal = new javax.swing.JLabel();
        jComboBoxNumeroSucursal = new javax.swing.JComboBox();
        jLabelTipoTurno = new javax.swing.JLabel();
        jComboBoxTipoTurno = new javax.swing.JComboBox();
        jPanelDatosEmpleado = new javax.swing.JPanel();
        jLabelIdEmpleado = new javax.swing.JLabel();
        jTextFieldIdEmpleado = new javax.swing.JTextField();
        jButtonBuscarEmpleado = new javax.swing.JButton();
        jLabelNombreEmpleado = new javax.swing.JLabel();
        jTextFieldNombreEmpleado = new javax.swing.JTextField();
        jTextFieldEspecializacion = new javax.swing.JTextField();
        jLabelEspecializacion = new javax.swing.JLabel();
        jButtonAceptarEmpleado = new javax.swing.JButton();
        jPanelDatosCliente = new javax.swing.JPanel();
        jTextFieldIdCliente = new javax.swing.JTextField();
        jLabelIdCliente = new javax.swing.JLabel();
        jLabelNombreCliente = new javax.swing.JLabel();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        jLabelApellidoCliente = new javax.swing.JLabel();
        jTextFieldApellidoCliente = new javax.swing.JTextField();
        jButtonBuscarCliente = new javax.swing.JButton();
        jLabelIdEquipo = new javax.swing.JLabel();
        jComboBoxIdEquipo = new javax.swing.JComboBox();
        jButtonAceptarCliente = new javax.swing.JButton();
        jDateChooserFecha = new com.toedter.calendar.JDateChooser();
        jLabelFecha = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jSpinnerHora = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jSpinnerMinuto = new javax.swing.JSpinner();
        jLabelTotalTurno = new javax.swing.JLabel();
        jTextFieldTotalTurno = new javax.swing.JTextField();
        JButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAceptarTurno = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Turnos"));

        jTableTurnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableTurnos);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );

        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");

        jButtonEliminar.setText("Eliminar");

        jButton1.setText("Finalizar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEliminar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevo)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonEliminar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del Turno"));

        jLabelIdTurno.setText("Id Turno:");

        jTextFieldIdTurno.setEditable(false);

        jLabelNumeroSucursal.setText("Nro de sucursal:");

        jComboBoxNumeroSucursal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelTipoTurno.setText("Tipo de Turno:");

        jComboBoxTipoTurno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanelDatosEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del Empleado"));

        jLabelIdEmpleado.setText("Id Empleado:");

        jButtonBuscarEmpleado.setText("Buscar");
        jButtonBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarEmpleadoActionPerformed(evt);
            }
        });

        jLabelNombreEmpleado.setText("Nombre:");

        jTextFieldNombreEmpleado.setEditable(false);

        jTextFieldEspecializacion.setEditable(false);

        jLabelEspecializacion.setText("Especializacion:");

        jButtonAceptarEmpleado.setText("Aceptar");
        jButtonAceptarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosEmpleadoLayout = new javax.swing.GroupLayout(jPanelDatosEmpleado);
        jPanelDatosEmpleado.setLayout(jPanelDatosEmpleadoLayout);
        jPanelDatosEmpleadoLayout.setHorizontalGroup(
            jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelIdEmpleado)
                    .addComponent(jLabelNombreEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelEspecializacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEspecializacion, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                        .addComponent(jButtonBuscarEmpleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAceptarEmpleado)))
                .addContainerGap())
        );
        jPanelDatosEmpleadoLayout.setVerticalGroup(
            jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdEmpleado)
                    .addComponent(jTextFieldIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarEmpleado)
                    .addComponent(jButtonAceptarEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreEmpleado)
                    .addComponent(jTextFieldNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEspecializacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEspecializacion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDatosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del Cliente"));

        jLabelIdCliente.setText("Id Cliente:");

        jLabelNombreCliente.setText("Nombre:");

        jTextFieldNombreCliente.setEditable(false);

        jLabelApellidoCliente.setText("Apellido:");

        jTextFieldApellidoCliente.setEditable(false);

        jButtonBuscarCliente.setText("Buscar");
        jButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClienteActionPerformed(evt);
            }
        });

        jLabelIdEquipo.setText("Id Equipo:");

        jComboBoxIdEquipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonAceptarCliente.setText("Aceptar");
        jButtonAceptarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosClienteLayout = new javax.swing.GroupLayout(jPanelDatosCliente);
        jPanelDatosCliente.setLayout(jPanelDatosClienteLayout);
        jPanelDatosClienteLayout.setHorizontalGroup(
            jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                        .addComponent(jLabelIdEquipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxIdEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                        .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNombreCliente)
                            .addComponent(jLabelIdCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIdCliente)
                            .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))))
                .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(jLabelApellidoCliente))
                    .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButtonBuscarCliente)
                        .addGap(0, 44, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAceptarCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelDatosClienteLayout.setVerticalGroup(
            jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdCliente)
                    .addComponent(jTextFieldIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarCliente)
                    .addComponent(jButtonAceptarCliente))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellidoCliente)
                    .addComponent(jTextFieldApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdEquipo)
                    .addComponent(jComboBoxIdEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelFecha.setText("Fecha:");

        jLabelHora.setText("Hora:");

        jSpinnerHora.setModel(new javax.swing.SpinnerNumberModel(8, 8, 19, 1));

        jLabel13.setText(":");

        jSpinnerMinuto.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabelTotalTurno.setText("Total: $");

        jTextFieldTotalTurno.setEditable(false);

        JButtonAceptar.setText("Aceptar");
        JButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonAceptarTurno.setText("Aceptar");
        jButtonAceptarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarTurnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabelTotalTurno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTotalTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(JButtonAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCancelar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNumeroSucursal)
                                    .addComponent(jLabelIdTurno))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldIdTurno, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(jComboBoxNumeroSucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabelFecha))
                                    .addComponent(jLabelTipoTurno))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelHora)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSpinnerMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBoxTipoTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonAceptarTurno))))
                            .addComponent(jPanelDatosCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelDatosEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelIdTurno)
                        .addComponent(jTextFieldIdTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelFecha)
                    .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelHora)
                        .addComponent(jLabel13)
                        .addComponent(jSpinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinnerMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNumeroSucursal)
                        .addComponent(jComboBoxNumeroSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTipoTurno)
                        .addComponent(jComboBoxTipoTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonAceptarTurno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatosEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalTurno)
                    .addComponent(jTextFieldTotalTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        // TODO add your handling code here:
        this.activarDatosTurnoPrincipio(true);
        this.jButtonCancelar.setEnabled(true);
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonAceptarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarTurnoActionPerformed
        // TODO add your handling code here:
        this.calcularTipoDeTurno();
        this.activarDatosTurnoPrincipio(false);
        this.activarDatosCliente(true);
        this.jButtonAceptarCliente.setEnabled(false);
    }//GEN-LAST:event_jButtonAceptarTurnoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.activarTodosLosDatosTurno(false);
        this.limpiarDatosTurno();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void JButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAceptarActionPerformed
        // TODO add your handling code here:
        this.activarTodosLosDatosTurno(false);
        this.limpiarDatosTurno();
    }//GEN-LAST:event_JButtonAceptarActionPerformed

    private void jButtonAceptarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarClienteActionPerformed
        // TODO add your handling code here:
        this.activarDatosCliente(false);
        this.activarDatosEmpleado(true);
        this.jButtonAceptarEmpleado.setEnabled(false);
    }//GEN-LAST:event_jButtonAceptarClienteActionPerformed

    private void jButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarClienteActionPerformed
        // TODO add your handling code here:
        if(this.jTextFieldIdCliente.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "INGRESE UN CODIGO PARA REALIZAR LA BUSQUEDA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);JOptionPane.showMessageDialog(null, "INGRESE UN CODIGO PARA REALIZAR LA BUSQUEDA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        else{
            List<Cliente> clientes = null;
            int idCliente = Integer.parseInt(this.jTextFieldIdCliente.getText());// leo y guardo el id de un cliente
            try {
                clientes = this.miLogica.dameClientes();
            } catch (PreexistingEntityException ex) {
                Logger.getLogger(VentanaTurno.class.getName()).log(Level.SEVERE, null, ex);
            }
            for(Cliente e : clientes){// recorro la lista de clientes
                if(e.isId(idCliente)){// si corresponde al id lo almaceno en unCliente
                    this.unCliente = e;
                }
            }
            if(this.unCliente != null){// verifico si encontro al cliente
                this.jButtonAceptarCliente.setEnabled(true);
                this.cargarComboBoxEquipo();// cargo el combobox de equipo
                this.jTextFieldNombreCliente.setText(this.unCliente.getNombre());// muestro el nombre del cliente
                this.jTextFieldApellidoCliente.setText(this.unCliente.getApellido());// muestro el apellido del cliente
            }
            else{// si no encuentro a un cliente con el idCliente
                JOptionPane.showMessageDialog(null, "NO EXISTE UN CLIENTE CON EL ID: "+idCliente, "ERROR", JOptionPane.ERROR_MESSAGE);
                this.jButtonAceptarCliente.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jButtonBuscarClienteActionPerformed

    private void jButtonAceptarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarEmpleadoActionPerformed
        // TODO add your handling code here:
        this.activarDatosEmpleado(false);
    }//GEN-LAST:event_jButtonAceptarEmpleadoActionPerformed

    private void jButtonBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarEmpleadoActionPerformed
        // TODO add your handling code here:
        if(this.jTextFieldIdEmpleado.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "INGRESE UN CODIGO PARA REALIZAR LA BUSQUEDA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        else{
            List<Empleado> empleados = null;
            int idEmpleado = Integer.parseInt(this.jTextFieldIdEmpleado.getText());// leo y guardo el id de un empleado
            try {
                empleados = this.miLogica.dameEmpleados();
            } catch (PreexistingEntityException ex) {
                Logger.getLogger(VentanaTurno.class.getName()).log(Level.SEVERE, null, ex);
            }
            for(Empleado e : empleados){// recorro la lista de empleados
                if(e.isId(idEmpleado)){// si corresponde al id lo almaceno en unEmpleado
                    this.unEmpleado = e;
                }
            }
            if(this.unEmpleado != null){// verifico si encontro al empleado
                this.jButtonAceptarEmpleado.setEnabled(true);
                this.cargarComboBoxEquipo();// cargo el combobox de equipo
                this.jTextFieldNombreEmpleado.setText(this.unEmpleado.getNombre());// muestro el nombre del cliente
                this.jTextFieldEspecializacion.setText(this.unEmpleado.getTipoEmpleado());// muestro el tipo de empleado
            }
            else{// si no encuentro a un cliente con el idCliente
                JOptionPane.showMessageDialog(null, "NO EXISTE UN EMPLEADO CON EL ID: "+idEmpleado, "ERROR", JOptionPane.ERROR_MESSAGE);
                this.jButtonAceptarEmpleado.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jButtonBuscarEmpleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAceptar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAceptarCliente;
    private javax.swing.JButton jButtonAceptarEmpleado;
    private javax.swing.JButton jButtonAceptarTurno;
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JButton jButtonBuscarEmpleado;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JComboBox jComboBoxIdEquipo;
    private javax.swing.JComboBox jComboBoxNumeroSucursal;
    private javax.swing.JComboBox jComboBoxTipoTurno;
    private com.toedter.calendar.JDateChooser jDateChooserFecha;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabelApellidoCliente;
    private javax.swing.JLabel jLabelEspecializacion;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelIdCliente;
    private javax.swing.JLabel jLabelIdEmpleado;
    private javax.swing.JLabel jLabelIdEquipo;
    private javax.swing.JLabel jLabelIdTurno;
    private javax.swing.JLabel jLabelNombreCliente;
    private javax.swing.JLabel jLabelNombreEmpleado;
    private javax.swing.JLabel jLabelNumeroSucursal;
    private javax.swing.JLabel jLabelTipoTurno;
    private javax.swing.JLabel jLabelTotalTurno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelDatosCliente;
    private javax.swing.JPanel jPanelDatosEmpleado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinnerHora;
    private javax.swing.JSpinner jSpinnerMinuto;
    private javax.swing.JTable jTableTurnos;
    private javax.swing.JTextField jTextFieldApellidoCliente;
    private javax.swing.JTextField jTextFieldEspecializacion;
    private javax.swing.JTextField jTextFieldIdCliente;
    private javax.swing.JTextField jTextFieldIdEmpleado;
    private javax.swing.JTextField jTextFieldIdTurno;
    private javax.swing.JTextField jTextFieldNombreCliente;
    private javax.swing.JTextField jTextFieldNombreEmpleado;
    private javax.swing.JTextField jTextFieldTotalTurno;
    // End of variables declaration//GEN-END:variables

    public void activarTodosLosDatosTurno(boolean b){
        this.activarDatosTurnoPrincipio(b);
        this.activarDatosCliente(b);
        this.activarDatosEmpleado(b);       
    }
    
    public void activarDatosTurnoPrincipio(boolean b){
         // Datos del turno
        this.jLabelIdTurno.setEnabled(b);
        this.jTextFieldIdTurno.setEnabled(b);
        this.jLabelTipoTurno.setEnabled(b);
        this.jComboBoxTipoTurno.setEnabled(b);
        this.jLabelNumeroSucursal.setEnabled(b);
        this.jComboBoxNumeroSucursal.setEnabled(b);
        this.jLabelFecha.setEnabled(b);
        this.jDateChooserFecha.setEnabled(b);
        this.jLabelHora.setEnabled(b);
        this.jSpinnerHora.setEnabled(b);
        this.jLabel13.setEnabled(b);
        this.jSpinnerMinuto.setEnabled(b);
        this.jButtonAceptarTurno.setEnabled(b);
    }
    
    public void activarDatosCliente(boolean b){
        // Datos del cliente
        this.jPanelDatosCliente.setEnabled(b);
        this.jLabelIdCliente.setEnabled(b);
        this.jTextFieldIdCliente.setEnabled(b);
        this.jButtonBuscarCliente.setEnabled(b);
        this.jLabelNombreCliente.setEnabled(b);
        this.jTextFieldNombreCliente.setEnabled(b);
        this.jLabelApellidoCliente.setEnabled(b);
        this.jTextFieldApellidoCliente.setEnabled(b);
        this.jLabelIdEquipo.setEnabled(b);
        this.jComboBoxIdEquipo.setEnabled(b);
        this.jButtonAceptarCliente.setEnabled(b);
    }
    
    public void activarDatosEmpleado(boolean b){
        // Datos del empleado
        this.jPanelDatosEmpleado.setEnabled(b);
        this.jLabelIdEmpleado.setEnabled(b);
        this.jTextFieldIdEmpleado.setEnabled(b);
        this.jButtonBuscarEmpleado.setEnabled(b);
        this.jLabelNombreEmpleado.setEnabled(b);
        this.jLabelEspecializacion.setEnabled(b);
        this.jTextFieldEspecializacion.setEnabled(b);
        this.jButtonAceptarEmpleado.setEnabled(b);
    }
    
    public void limpiarDatosTurno(){
        // Datos del turno
        this.jTextFieldIdTurno.setText("");
        this.jComboBoxTipoTurno.setSelectedIndex(0);
        this.jComboBoxNumeroSucursal.setSelectedIndex(0);
        this.jDateChooserFecha.setCalendar(null);
        this.jSpinnerHora.setValue(8);
        this.jSpinnerMinuto.setValue(0);
        // Datos del cliente
        this.jTextFieldIdCliente.setText("");
        this.jTextFieldNombreCliente.setText("");
        this.jTextFieldApellidoCliente.setText("");
        this.jComboBoxIdEquipo.setSelectedIndex(0);
        // Datos del empleado
        this.jTextFieldIdEmpleado.setText("");
        this.jTextFieldNombreEmpleado.setText("");
        this.jTextFieldEspecializacion.setText("");
        // Final
        this.jTextFieldTotalTurno.setText("");
        // limpio las variables
        this.unCliente = null;
        this.unEmpleado = null;
        this.unArticulo = null;
        // limpio todas las listas
        this.idArticulos.clear();
        this.cantidades.clear();
        this.descipcionDetalle.clear();
        this.nombres.clear();
        this.precios.clear();
    }
    
    public void cargarComboBoxSucursal() throws PreexistingEntityException{
        List<Sucursal> sucursales = this.miLogica.dameSucursales();
        for(Sucursal e : sucursales){
            this.modeloComboBoxSucursal.addElement(e.getNumeroSucursal());
        }
        this.jComboBoxNumeroSucursal.setModel(modeloComboBoxSucursal);
    }
    
    public void cargarComboBoxTipoTurno(){
        this.modeloComboBoxTipoTurno.addElement("Reparacion");
        this.modeloComboBoxTipoTurno.addElement("Mantenimiento");
        this.modeloComboBoxTipoTurno.addElement("Diagnostico");
        this.jComboBoxTipoTurno.setModel(modeloComboBoxTipoTurno);
    }
    
    public void cargarComboBoxEquipo(){
        List<Equipo> equipos = this.unCliente.getEquipos();
        for(Equipo e : equipos){
            this.modeloComboBoxIdEquipo.addElement(e.getId());
        }
        this.jComboBoxIdEquipo.setModel(modeloComboBoxIdEquipo);
    }
    
    public void calcularTotal(){
        float total = Float.valueOf(this.jTextFieldTotalTurno.getText());
        int i = 0;// indice
        for(Integer e : this.idArticulos){
            total = total + (this.cantidades.get(i) * this.precios.get(i));
            i++;
        }
        this.jTextFieldTotalTurno.setText(String.valueOf(total));
    }
    
    public void calcularTipoDeTurno(){
        String tipoTurno = this.jComboBoxTipoTurno.getSelectedItem().toString();// obtengo el tipo de turno
        /*
        * Los precios de cada tipo de turno son:
        * Reparacion = $400
        * Mantenimiento = $250
        * Diagnostico = $150
        */
        if(tipoTurno.equalsIgnoreCase("Reparacion")){
            this.jTextFieldTotalTurno.setText("400.00");
        }
        if(tipoTurno.equalsIgnoreCase("Mantenimiento")){
            this.jTextFieldTotalTurno.setText("250.00");
        }
        if(tipoTurno.equalsIgnoreCase("Diagnostico")){
            this.jTextFieldTotalTurno.setText("150.00");
        }
    }
}
