/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logicaDeNegocio.Articulo;
import logicaDeNegocio.Cliente;
import logicaDeNegocio.FacturaVenta;
import logicaDeNegocio.Sucursal;
import persistenciaJPA.exceptions.NonexistentEntityException;
import persistenciaJPA.exceptions.PreexistingEntityException;

/**
 *
 * @author Choni
 */
public class VentanaFacturaVenta extends javax.swing.JInternalFrame {
    //CONTROLADORA DE LA INTERFAZ
    private ControladoraInterfaz miLogica;
    private DefaultTableModel modeloFacturaVenta = new DefaultTableModel(){
        // sobreescribo el metodo para que no se modifiquen los campos de las filas en la tabla
        @Override
        public boolean isCellEditable(int rowIndex, int colIndex){
            return false;
        }
    };
    private DefaultTableModel modeloDetalles = new DefaultTableModel(){
        // sobreescribo el metodo para que no se modifiquen los campos de las filas en la tabla
        @Override
        public boolean isCellEditable(int rowIndex, int colIndex){
            return false;
        }
    };
    private DefaultComboBoxModel modeloComboBoxSucursales = new DefaultComboBoxModel();
    private DefaultComboBoxModel modeloComboBoxTipoDePago = new DefaultComboBoxModel();
    private SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");//formato para la fecha
    private Date fechaLocal = new Date ();// de aca obtengo la fecha del sistema
    private String fecha;
    private List<Integer> misCantidadDetalles = null;// cantidades de cada articulo en cada detalle
    private List<Articulo> articulos = null;// lista de articulos para cada detalle
    private List<Articulo> articulosPersistencia = null;// lista de articulos de la persistencia
    private Cliente unCliente = null;
    private Articulo miArticulo = null;
    private String modoPago;
    
    /**
     * Creates new form VentanaFacturaVenta
     */
    public VentanaFacturaVenta(ControladoraInterfaz unaControladoraInterfaz) throws PreexistingEntityException {
        this.miLogica = unaControladoraInterfaz;
        initComponents();
        this.setClosable(true);// boton para cerrar
        this.setIconifiable(true);// boton para minimizar
        // Cabecera de la tabla factura de venta
        modeloFacturaVenta.addColumn("Id");
        modeloFacturaVenta.addColumn("Fecha");
        modeloFacturaVenta.addColumn("Hora");
        modeloFacturaVenta.addColumn("Cliente Nombre");
        modeloFacturaVenta.addColumn("Cliente Apellido");
        modeloFacturaVenta.addColumn("Total");
        this.jTableFacturasVentas.setModel(modeloFacturaVenta);
        // Cabecera de la tabla detalles
        modeloDetalles.addColumn("Producto");
        modeloDetalles.addColumn("Cantidad");
        modeloDetalles.addColumn("Precio Unitario");
        modeloDetalles.addColumn("Descuento");
        modeloDetalles.addColumn("Precio Total");
        this.jTableDetalles.setModel(modeloDetalles);
        
        this.misCantidadDetalles = new LinkedList<Integer>();
        this.articulos = new LinkedList<Articulo>();
        
        this.cargarComboBoxSucursales();
        this.activarDatosEmpresa(false);
        this.activarDatosCliente(false);
        this.activarModoPago(false);
        this.activarDatosProducto(false);
        this.cargarFacturasVentas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanelDatosEmpresa = new javax.swing.JPanel();
        jLabelTipoFactura = new javax.swing.JLabel();
        jTextFieldTipoDeFactura = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabelLocalidad = new javax.swing.JLabel();
        jTextFieldLocalidad = new javax.swing.JTextField();
        jLabelProvincia = new javax.swing.JLabel();
        jTextFieldProvincia = new javax.swing.JTextField();
        jLabelSucursal = new javax.swing.JLabel();
        jComboBoxSucursal = new javax.swing.JComboBox();
        jLabelCuit = new javax.swing.JLabel();
        jTextFieldCuit = new javax.swing.JTextField();
        jLabelIdFacturaVenta = new javax.swing.JLabel();
        jTextFieldIdFacturaVenta = new javax.swing.JTextField();
        jLabelFecha = new javax.swing.JLabel();
        jTextFieldFecha = new javax.swing.JTextField();
        jTextFieldHora = new javax.swing.JTextField();
        jLabelHora = new javax.swing.JLabel();
        jButtonAceptarSucursal = new javax.swing.JButton();
        jPanelDatosCliente = new javax.swing.JPanel();
        jLabelIdCliente = new javax.swing.JLabel();
        jTextFieldIdCliente = new javax.swing.JTextField();
        jButtonBuscarCliente = new javax.swing.JButton();
        jLabelNombreCliente = new javax.swing.JLabel();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        jLabelApellidoCliente = new javax.swing.JLabel();
        jTextFieldApellidoCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDetalles = new javax.swing.JTable();
        jPanelAgregarProducto = new javax.swing.JPanel();
        jLabelIdProducto = new javax.swing.JLabel();
        jTextFieldIdProducto = new javax.swing.JTextField();
        jButtonBuscarProducto = new javax.swing.JButton();
        jLabelNombreProducto = new javax.swing.JLabel();
        jTextFieldNombreProducto = new javax.swing.JTextField();
        jLabelCantidad = new javax.swing.JLabel();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jButtonAgregar = new javax.swing.JButton();
        jButtonQuitar = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jPanelModoPago = new javax.swing.JPanel();
        jComboBoxModoPago = new javax.swing.JComboBox();
        jLabelPago = new javax.swing.JLabel();
        jButtonAceptarPago = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonNuevo = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFacturasVentas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos de Factura de Venta"));

        jPanelDatosEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos de la Empresa"));

        jLabelTipoFactura.setText("Tipo de Factura:");

        jTextFieldTipoDeFactura.setEditable(false);

        jLabelDireccion.setText("Direccion:");

        jTextFieldDireccion.setEditable(false);

        jLabelLocalidad.setText("Localidad:");

        jTextFieldLocalidad.setEditable(false);

        jLabelProvincia.setText("Provincia:");

        jTextFieldProvincia.setEditable(false);

        jLabelSucursal.setText("Sucursal:");

        jComboBoxSucursal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelCuit.setText("C.U.I.T.:");

        jTextFieldCuit.setEditable(false);

        jLabelIdFacturaVenta.setText("Nro. Factura:");

        jTextFieldIdFacturaVenta.setEditable(false);

        jLabelFecha.setText("Fecha:");

        jTextFieldFecha.setEditable(false);

        jTextFieldHora.setEditable(false);

        jLabelHora.setText("Hora:");

        jButtonAceptarSucursal.setText("Aceptar");
        jButtonAceptarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarSucursalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosEmpresaLayout = new javax.swing.GroupLayout(jPanelDatosEmpresa);
        jPanelDatosEmpresa.setLayout(jPanelDatosEmpresaLayout);
        jPanelDatosEmpresaLayout.setHorizontalGroup(
            jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosEmpresaLayout.createSequentialGroup()
                .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDatosEmpresaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosEmpresaLayout.createSequentialGroup()
                                .addComponent(jLabelLocalidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatosEmpresaLayout.createSequentialGroup()
                                .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTipoFactura)
                                    .addComponent(jLabelDireccion, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDatosEmpresaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosEmpresaLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jTextFieldTipoDeFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanelDatosEmpresaLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabelProvincia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldProvincia)))
                .addGap(29, 29, 29)
                .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelFecha)
                        .addComponent(jLabelIdFacturaVenta))
                    .addGroup(jPanelDatosEmpresaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSucursal)
                            .addComponent(jLabelCuit))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldIdFacturaVenta, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatosEmpresaLayout.createSequentialGroup()
                        .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelHora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldHora, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldCuit, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatosEmpresaLayout.createSequentialGroup()
                        .addComponent(jComboBoxSucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAceptarSucursal)))
                .addContainerGap())
        );
        jPanelDatosEmpresaLayout.setVerticalGroup(
            jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoFactura)
                    .addComponent(jTextFieldTipoDeFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSucursal)
                    .addComponent(jComboBoxSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAceptarSucursal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDireccion)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCuit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLocalidad)
                    .addComponent(jLabelIdFacturaVenta)
                    .addComponent(jTextFieldLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIdFacturaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProvincia)
                    .addComponent(jTextFieldProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFecha)
                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHora)
                    .addComponent(jTextFieldHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDatosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del Cliente"));

        jLabelIdCliente.setText("Id Cliente:");

        jButtonBuscarCliente.setText("Buscar");
        jButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClienteActionPerformed(evt);
            }
        });

        jLabelNombreCliente.setText("Nombre:");

        jTextFieldNombreCliente.setEditable(false);

        jLabelApellidoCliente.setText("Apellido:");

        jTextFieldApellidoCliente.setEditable(false);

        javax.swing.GroupLayout jPanelDatosClienteLayout = new javax.swing.GroupLayout(jPanelDatosCliente);
        jPanelDatosCliente.setLayout(jPanelDatosClienteLayout);
        jPanelDatosClienteLayout.setHorizontalGroup(
            jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelIdCliente)
                    .addComponent(jLabelNombreCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(jTextFieldIdCliente))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                        .addComponent(jLabelApellidoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBuscarCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosClienteLayout.setVerticalGroup(
            jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdCliente)
                    .addComponent(jTextFieldIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreCliente)
                    .addComponent(jTextFieldApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelApellidoCliente))
                .addContainerGap())
        );

        jTableDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableDetalles);

        jPanelAgregarProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Agregar Producto"));

        jLabelIdProducto.setText("Id. Producto:");

        jButtonBuscarProducto.setText("Buscar");
        jButtonBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarProductoActionPerformed(evt);
            }
        });

        jLabelNombreProducto.setText("Nombre Producto:");

        jTextFieldNombreProducto.setEditable(false);

        jLabelCantidad.setText("Cantidad:");

        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1000, 1));

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonQuitar.setText("Quitar");
        jButtonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAgregarProductoLayout = new javax.swing.GroupLayout(jPanelAgregarProducto);
        jPanelAgregarProducto.setLayout(jPanelAgregarProductoLayout);
        jPanelAgregarProductoLayout.setHorizontalGroup(
            jPanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgregarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAgregar)
                    .addGroup(jPanelAgregarProductoLayout.createSequentialGroup()
                        .addGroup(jPanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNombreProducto)
                            .addComponent(jLabelIdProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAgregarProductoLayout.createSequentialGroup()
                                .addComponent(jTextFieldIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBuscarProducto))
                            .addGroup(jPanelAgregarProductoLayout.createSequentialGroup()
                                .addComponent(jTextFieldNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jLabelCantidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonQuitar)
                .addContainerGap())
        );
        jPanelAgregarProductoLayout.setVerticalGroup(
            jPanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgregarProductoLayout.createSequentialGroup()
                .addGroup(jPanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdProducto)
                    .addComponent(jTextFieldIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombreProducto)
                    .addGroup(jPanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCantidad)
                        .addComponent(jSpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregar)
                    .addComponent(jButtonQuitar))
                .addContainerGap())
        );

        jLabelTotal.setText("Total: $");

        jTextFieldTotal.setEditable(false);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jPanelModoPago.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Modo de Pago"));

        jComboBoxModoPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Efectivo", "Cta. Corriente" }));

        jLabelPago.setText("Pago:");

        jButtonAceptarPago.setText("Aceptar");
        jButtonAceptarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelModoPagoLayout = new javax.swing.GroupLayout(jPanelModoPago);
        jPanelModoPago.setLayout(jPanelModoPagoLayout);
        jPanelModoPagoLayout.setHorizontalGroup(
            jPanelModoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModoPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxModoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelModoPagoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButtonAceptarPago)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelModoPagoLayout.setVerticalGroup(
            jPanelModoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModoPagoLayout.createSequentialGroup()
                .addGroup(jPanelModoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxModoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAceptarPago)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanelAgregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelDatosEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanelDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelModoPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabelTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanelDatosEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDatosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelModoPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotal)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Facturas de Ventas"));

        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jTableFacturasVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableFacturasVentas);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEliminar)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevo)
                    .addComponent(jButtonEliminar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarClienteActionPerformed
        // TODO add your handling code here:
        if(this.jTextFieldIdCliente.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "INGRESE UN CODIGO PARA REALIZAR LA BUSQUEDA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);JOptionPane.showMessageDialog(null, "INGRESE UN CODIGO PARA REALIZAR LA BUSQUEDA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        else{
            List<Cliente> clientes = null;
            int idCliente = Integer.parseInt(this.jTextFieldIdCliente.getText());// leo y guardo el id de un cliente
            try {
                clientes = this.miLogica.dameClientes();
            } catch (PreexistingEntityException ex) {
                Logger.getLogger(VentanaTurno.class.getName()).log(Level.SEVERE, null, ex);
            }
            for(Cliente e : clientes){// recorro la lista de clientes
                if(e.isId(idCliente)){// si corresponde al id lo almaceno en unCliente
                    this.unCliente = e;
                }
            }
            if(this.unCliente != null){// verifico si encontro al cliente
                this.activarModoPago(true);
                this.activarDatosCliente(false);
                if(unCliente.getCondicionCliente()){
                    this.jTextFieldTipoDeFactura.setText("Factura");
                }else{
                    this.jTextFieldTipoDeFactura.setText("Ticket");
                }
                this.jTextFieldNombreCliente.setText(this.unCliente.getNombre());// muestro el nombre del cliente
                this.jTextFieldApellidoCliente.setText(this.unCliente.getApellido());// muestro el apellido del cliente
            }
            else{// si no encuentro a un cliente con el idCliente
                JOptionPane.showMessageDialog(null, "NO EXISTE UN CLIENTE CON EL ID: "+idCliente, "ERROR", JOptionPane.ERROR_MESSAGE);
                this.activarDatosCliente(true);
            }
        }
    }//GEN-LAST:event_jButtonBuscarClienteActionPerformed

    private void jButtonBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarProductoActionPerformed
        // TODO add your handling code here:
        if(this.jTextFieldIdProducto.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "INGRESE UN CODIGO PARA REALIZAR LA BUSQUEDA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        else{
            try {
                this.articulosPersistencia = this.miLogica.dameArticulos();
            } catch (PreexistingEntityException ex) {
                Logger.getLogger(VentanaFacturaCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
            boolean encontrar = false;//bandera para encontrar
            for(Articulo e : this.articulosPersistencia){
                if(e.isId(Integer.parseInt(this.jTextFieldIdProducto.getText()))){
                    encontrar = true;// cambio mi bandera a verdadero porque encontro
                    this.miArticulo = e;// si encuentro el articulo, lo guardo en miArticulo
                    this.jTextFieldNombreProducto.setText(e.getNombre());// muestro el nombre del producto
                    this.activarCantidad(true);// activo mi jspinner para poner la cantidad
                }
            }
            if(encontrar == false){
                JOptionPane.showMessageDialog(null, "NO SE ENCONTRO NINGUN ARTICULO CON EL CODIGO: "+ this.jTextFieldIdProducto.getText(), "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                this.miArticulo = null;// si no encuentro el articulo, miArticulo apunta a null
            }
        }
    }//GEN-LAST:event_jButtonBuscarProductoActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
        int cantidadProducto = Integer.valueOf(this.jSpinnerCantidad.getValue().toString());// almaceno la cantidad del articulo
        if(this.miArticulo != null){// verifico si encontro un articulo
            if(miArticulo.esMenorOIgualCantidadoRequerida(cantidadProducto)){// verifico si la cantidad requerida es igual o menor a la cantidad en stock
                // limpio los campos para buscar un nuevo articulo
                this.jTextFieldNombreProducto.setText("");
                this.jTextFieldIdProducto.setText("");
                // agrego un articulo a la lista de compras
                this.articulos.add(miArticulo);
                this.misCantidadDetalles.add(cantidadProducto);
                // desactivo la cantidad
                this.activarCantidad(false);
                this.jSpinnerCantidad.setValue(1);// reseteo la cantidad
                this.actualizarDetalles();
                this.calcularTotal();// calculo el total
                this.miArticulo = null;
            }
            else{
                JOptionPane.showMessageDialog(null, "LA CANTIDAD A COMPRAR ES MAYOR DE LO QUE EXISTE EN STOCK", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }
        }
        else{// si nunca se busco un articulo, lo informo
            JOptionPane.showMessageDialog(null, "NO SE BUSCO NINGUN ARTICULO", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        this.activarBotonAceptar();
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarActionPerformed
        // TODO add your handling code here:
        int seleccionDetalle = this.jTableDetalles.getSelectedRow();
        int i = 1;
        if(seleccionDetalle < 0){// si no se selecciono ninguna fila
            JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE UNA FILA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        else{
            i = JOptionPane.showConfirmDialog(this, "Estas Seguro ?", "Vas a Eliminar un Detalle", JOptionPane.YES_NO_OPTION);
            if(i == 0){
                this.eliminarDetalle(seleccionDetalle);
                this.calcularTotal();
            }
        }
        this.activarBotonAceptar();
    }//GEN-LAST:event_jButtonQuitarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        this.crearFactura();
        this.activarDatosEmpresa(false);
        this.activarDatosCliente(false);
        this.activarModoPago(false);
        this.activarDatosProducto(false);
        this.activarBotonAceptar();
        this.jButtonCancelar.setEnabled(false);
        this.limpiarDatosCliente();
        this.limpiarDatosDetalle();
        this.limpiarDatosEmpresa(true);
        try {
            this.actualizarFacturasVentas();
        } catch (PreexistingEntityException ex) {
            Logger.getLogger(VentanaArticulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.articulos = null;
        this.misCantidadDetalles = null;
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
//        // TODO add your handling code here:
//        this.jSpinnerCantidad.setValue(1);// reseteo la cantidad
//        this.limpiarDatosFacturaCompra();
//        this.activarDatosFacturaCompra(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarSucursalActionPerformed
        int numeroSucursal = Integer.parseInt(this.jComboBoxSucursal.getSelectedItem().toString());
        List<Sucursal> sucursales = null;
        try {
            sucursales = this.miLogica.dameSucursales();
        } catch (PreexistingEntityException ex) {
            Logger.getLogger(VentanaFacturaVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(Sucursal e : sucursales){
            if(e.isSucursal(numeroSucursal)){
                this.jTextFieldDireccion.setText(e.getDireccion());
                this.activarDatosCliente(true);
                this.activarDatosEmpresa(false);
            }
        }
    }//GEN-LAST:event_jButtonAceptarSucursalActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        // TODO add your handling code here:
        this.activarDatosEmpresa(true);
        this.jButtonCancelar.setEnabled(true);
        this.limpiarDatosEmpresa(true);
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonAceptarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarPagoActionPerformed
        // TODO add your handling code here:
        this.activarModoPago(false);
        this.modoPago = this.jComboBoxModoPago.getSelectedItem().toString();
        this.activarDatosProducto(true);
        this.calcularTotal();
    }//GEN-LAST:event_jButtonAceptarPagoActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        int seleccionArticulo = this.jTableFacturasVentas.getSelectedRow();
        int i = 1;
        if(seleccionArticulo == -1){// si no se selecciono nada de la tabla
            JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE UNA FILA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        else{
            i = JOptionPane.showConfirmDialog(this, "Estas Seguro ?", "Vas a Eliminar una Factura de Venta", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                try {
                    int id = Integer.parseInt(this.jTableFacturasVentas.getValueAt(seleccionArticulo, 0).toString());
                    this.miLogica.eliminarFacturaVenta(id);
                    // elimino mi factura de compra de la tabla
                    DefaultTableModel dtm = (DefaultTableModel) jTableFacturasVentas.getModel();
                    dtm.removeRow(jTableFacturasVentas.getSelectedRow()); 
                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(VentanaTique.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(VentanaTique.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonAceptarPago;
    private javax.swing.JButton jButtonAceptarSucursal;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JButton jButtonBuscarProducto;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JButton jButtonQuitar;
    private javax.swing.JComboBox jComboBoxModoPago;
    private javax.swing.JComboBox jComboBoxSucursal;
    private javax.swing.JLabel jLabelApellidoCliente;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCuit;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelIdCliente;
    private javax.swing.JLabel jLabelIdFacturaVenta;
    private javax.swing.JLabel jLabelIdProducto;
    private javax.swing.JLabel jLabelLocalidad;
    private javax.swing.JLabel jLabelNombreCliente;
    private javax.swing.JLabel jLabelNombreProducto;
    private javax.swing.JLabel jLabelPago;
    private javax.swing.JLabel jLabelProvincia;
    private javax.swing.JLabel jLabelSucursal;
    private javax.swing.JLabel jLabelTipoFactura;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAgregarProducto;
    private javax.swing.JPanel jPanelDatosCliente;
    private javax.swing.JPanel jPanelDatosEmpresa;
    private javax.swing.JPanel jPanelModoPago;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JTable jTableDetalles;
    private javax.swing.JTable jTableFacturasVentas;
    private javax.swing.JTextField jTextFieldApellidoCliente;
    private javax.swing.JTextField jTextFieldCuit;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldHora;
    private javax.swing.JTextField jTextFieldIdCliente;
    private javax.swing.JTextField jTextFieldIdFacturaVenta;
    private javax.swing.JTextField jTextFieldIdProducto;
    private javax.swing.JTextField jTextFieldLocalidad;
    private javax.swing.JTextField jTextFieldNombreCliente;
    private javax.swing.JTextField jTextFieldNombreProducto;
    private javax.swing.JTextField jTextFieldProvincia;
    private javax.swing.JTextField jTextFieldTipoDeFactura;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables

    public void limpiarDatosEmpresa(boolean b){
        if(b){
            this.jTextFieldLocalidad.setText("Posadas");
            this.jTextFieldProvincia.setText("Misiones");
            this.jTextFieldCuit.setText("30-711224360-3"); 
            //obtengo la fecha en un string
            this.fecha = fechaLocal.toLocaleString();
            //leo y almaceno la fecha y hora para crear mi tique
            String fecha = this.fecha.substring(0, 10);//codigo para obtener la fecha
            String hora = this.fecha.substring(11, 16);// codigo para obtener la hora
            this.jTextFieldFecha.setText(fecha);
            this.jTextFieldHora.setText(hora);            
        }
        else{
            this.jTextFieldTipoDeFactura.setText("");
            this.jTextFieldDireccion.setText("");
            this.jTextFieldLocalidad.setText("");
            this.jTextFieldProvincia.setText("");
            this.jComboBoxSucursal.setSelectedIndex(0);
            this.jTextFieldIdFacturaVenta.setText("");
            this.jTextFieldCuit.setText("");
            this.jTextFieldFecha.setText("");
            this.jTextFieldHora.setText("");
        }
    }
    
    public void limpiarDatosCliente(){
        this.jTextFieldIdCliente.setText("");
        this.jTextFieldNombreCliente.setText("");
        this.jTextFieldApellidoCliente.setText("");
        this.jComboBoxModoPago.setSelectedIndex(0);
    }
    
    public void limpiarDatosDetalle(){
        this.jTextFieldIdProducto.setText("");
        this.jTextFieldNombreProducto.setText("");
        this.jSpinnerCantidad.setValue(1);
        // borro todos los detalles de la factura de venta
        DefaultTableModel modelo = (DefaultTableModel) jTableDetalles.getModel();
        int filas = jTableDetalles.getRowCount();
        for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
        }
        this.jTextFieldTotal.setText("");
    }
    
    public void cargarComboBoxSucursales() throws PreexistingEntityException{
        List<Sucursal> sucursales = this.miLogica.dameSucursales();
        for(Sucursal e : sucursales){
            this.modeloComboBoxSucursales.addElement(e.getNumeroSucursal());
        }
        this.jComboBoxSucursal.setModel(modeloComboBoxSucursales);
        //this.jComboBoxSucursalBuscar.setModel(modeloComboBox);
    }
    
    public void activarDatosEmpresa(boolean b){
        this.jPanelDatosEmpresa.setEnabled(b);
        this.jLabelTipoFactura.setEnabled(b);
        this.jLabelDireccion.setEnabled(b);
        this.jLabelLocalidad.setEnabled(b);
        this.jLabelProvincia.setEnabled(b);
        this.jLabelSucursal.setEnabled(b);
        this.jLabelCuit.setEnabled(b);
        this.jLabelIdFacturaVenta.setEnabled(b);
        this.jLabelFecha.setEnabled(b);
        this.jLabelHora.setEnabled(b);
        this.jTextFieldTipoDeFactura.setEnabled(b);
        this.jTextFieldDireccion.setEnabled(b);
        this.jTextFieldLocalidad.setEnabled(b);
        this.jTextFieldProvincia.setEnabled(b);
        this.jComboBoxSucursal.setEnabled(b);
        this.jButtonAceptarSucursal.setEnabled(b);
        this.jTextFieldCuit.setEnabled(b);
        this.jTextFieldIdFacturaVenta.setEnabled(b);
        this.jTextFieldFecha.setEnabled(b);
        this.jTextFieldHora.setEnabled(b);
    }
    
    public void activarDatosCliente(boolean b){
        this.jPanelDatosCliente.setEnabled(b);
        this.jLabelIdCliente.setEnabled(b);
        this.jTextFieldIdCliente.setEnabled(b);
        this.jLabelNombreCliente.setEnabled(b);
        this.jLabelApellidoCliente.setEnabled(b);
        this.jButtonBuscarCliente.setEnabled(b);
    }
    
    public void activarModoPago(boolean b){
        this.jPanelModoPago.setEnabled(b);
        this.jLabelPago.setEnabled(b);
        this.jComboBoxModoPago.setEnabled(b);
        this.jButtonAceptarPago.setEnabled(b);
    }
    
    public void activarDatosProducto(boolean b){
        this.jPanelAgregarProducto.setEnabled(b);
        this.jLabelIdProducto.setEnabled(b);
        this.jLabelNombreProducto.setEnabled(b);
        this.jLabelCantidad.setEnabled(b);
        this.jTextFieldIdProducto.setEnabled(b);
        this.jButtonBuscarProducto.setEnabled(b);
        this.jTextFieldNombreProducto.setEnabled(b);
        this.jSpinnerCantidad.setEnabled(b);
        this.jButtonAgregar.setEnabled(b);
        this.jButtonQuitar.setEnabled(b);
        this.jButtonAceptar.setEnabled(b);
        this.jButtonCancelar.setEnabled(b);
    }
    
    public void activarBotonAceptar(){
        if(this.misCantidadDetalles.isEmpty()){
            this.jButtonAceptar.setEnabled(false);
        }
        else{
            this.jButtonAceptar.setEnabled(true);
        }
    }
    
    public void calcularTotal(){
        float total = 0;
        if(this.articulos != null){
            int i = 0;// indice
            if(this.unCliente.getCondicionCliente()){// true = mayorista
                for(Articulo e : this.articulos){
                    float descuento = Float.parseFloat(this.jTableDetalles.getValueAt(i, 3).toString());// fila i, columna 3
                    float descuentoTotal = e.getPrecioVenta() * descuento;
                    total = total + ((e.getPrecioVenta() - descuentoTotal) * this.misCantidadDetalles.get(i));
                }
            }
            else{
                for(Articulo e : this.articulos){
                    total = total + (e.getPrecioVenta() * this.misCantidadDetalles.get(i));
                    i++;
                }
            }
            this.jTextFieldTotal.setText(String.valueOf(total));
        }
        else{
            this.jTextFieldTotal.setText("0.0");
        }
    }
    
    public void activarCantidad(boolean b){        
        this.jSpinnerCantidad.setEnabled(b);
    }
    
    public void actualizarDetalles(){// borro todos los detalles uno a uno
        DefaultTableModel modelo = (DefaultTableModel) jTableDetalles.getModel();
        int filas = jTableDetalles.getRowCount();
        for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
        }
        this.cargarDetalles();
    }
    
    public void cargarDetalles(){
        int i = 0;
        Object[]fila = new Object[5];
        for(Articulo e : articulos){
            fila[0] = e.getNombre();
            fila[1] = this.misCantidadDetalles.get(i);
            fila[2] = e.getPrecioVenta();
            float descuento = e.getPrecioVenta() * e.getDescuentoMayorista();
            fila[3] = descuento;
            fila[4] = (this.misCantidadDetalles.get(i) * descuento);
            this.modeloDetalles.addRow(fila);
            this.jTableDetalles.setModel(modeloDetalles);
            i++;
        }
    }
    
    public void eliminarDetalle(int i){
        this.articulos.remove(i);
        this.misCantidadDetalles.remove(i);
        DefaultTableModel dtm = (DefaultTableModel) jTableDetalles.getModel();
        dtm.removeRow(jTableDetalles.getSelectedRow()); 
    }
    
    public void crearFactura(){
        Cliente unCliente = this.unCliente;
        String tipoComprobante;
        if(unCliente.getCondicionCliente()){
            tipoComprobante = "Factura";
        }else{
            tipoComprobante = "Ticket";
        }
        String fechaCorta = this.jTextFieldFecha.getText();
        String horaFactura = this.jTextFieldHora.getText();
        List<Articulo> articulos = null;
        articulos = this.articulos;
        List<Integer> cantidadDetalles = null;
        cantidadDetalles = this.misCantidadDetalles;
        int sucursal = Integer.parseInt(this.jComboBoxSucursal.getSelectedItem().toString());
        float total = Float.parseFloat(this.jTextFieldTotal.getText());
        String modoPago = this.jComboBoxModoPago.getSelectedItem().toString();
        try {
            this.miLogica.crearFacturaVenta(fechaCorta, horaFactura, articulos, cantidadDetalles, total, sucursal, modoPago, unCliente, tipoComprobante);
        } catch (Exception ex) {
            Logger.getLogger(VentanaTique.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.misCantidadDetalles.clear();// limpio mi lista de cantidades
        this.articulos.clear();// limpio mi lista de articulos
        this.unCliente = null;// limpio mi objeto cliente
    }
    
    public void cargarFacturasVentas() throws PreexistingEntityException{
        List<FacturaVenta> facturasCompras = this.miLogica.dameFacturasVentas();
        Object[]fila= new Object[6];
        for(FacturaVenta e : facturasCompras){
                fila[0] = e.getIdComprobante();
                fila[1] = e.getFechaComprobante();
                fila[2] = e.getHoraComprobante();
                fila[3] = e.getUnCliente().getNombre(); 
                fila[4] = e.getUnCliente().getApellido(); 
                fila[5] = e.getTotalComprobante();
                this.modeloFacturaVenta.addRow(fila);
                this.jTableFacturasVentas.setModel(modeloFacturaVenta);
        }
    }
    
    public void actualizarFacturasVentas() throws PreexistingEntityException{
        DefaultTableModel modelo = (DefaultTableModel) jTableFacturasVentas.getModel();
        int filas = jTableFacturasVentas.getRowCount();
        for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
        }
        this.cargarFacturasVentas();
    }
}
