/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logicaDeNegocio.Cliente;
import logicaDeNegocio.Equipo;
import persistenciaJPA.exceptions.NonexistentEntityException;
import persistenciaJPA.exceptions.PreexistingEntityException;

/**
 *
 * @author Choni
 */
public class VentanaEquipo extends javax.swing.JInternalFrame {
    //CONTROLADORA DE LA INTERFAZ
    private ControladoraInterfaz miLogica;
    private DefaultTableModel modeloEquipo = new DefaultTableModel(){
        // sobreescribo el metodo para que no se modifiquen los campos de las filas en la tabla
        @Override
        public boolean isCellEditable(int rowIndex, int colIndex){
            return false;
        }
    };
    private int banderaModificar;//bandera de modificacion
    private Cliente unCliente = null;
    
    
    /**
     * Creates new form VentanaEquipo
     */
    public VentanaEquipo(ControladoraInterfaz unaControladoraInterfaz) throws PreexistingEntityException {
        initComponents();
        this.miLogica = unaControladoraInterfaz;
        banderaModificar = -1;
        // manejo de la ventana
        this.setClosable(true);
        this.setIconifiable(true);
        /// Agregar las cabeceras de la tabla
        modeloEquipo.addColumn("Id Equipo");
        modeloEquipo.addColumn("Marca Equipo");
        modeloEquipo.addColumn("Id Cliente");
        modeloEquipo.addColumn("Nombre Cliente");
        modeloEquipo.addColumn("Apellido Cliente");
        this.jTableEquipos.setModel(modeloEquipo);
        
        this.activarDatosCliente(false);
        this.activarDatosEquipo(false);
        this.cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDatosEquipo = new javax.swing.JPanel();
        jButtonAceptarEquipo = new javax.swing.JButton();
        jButtonCancelarEquipo = new javax.swing.JButton();
        jLabelIdEquipo = new javax.swing.JLabel();
        jTextFieldIdEquipo = new javax.swing.JTextField();
        jLabelMarcaEquipo = new javax.swing.JLabel();
        jTextFieldMarcaEquipo = new javax.swing.JTextField();
        jLabelAnioEquipo = new javax.swing.JLabel();
        jTextFieldAnioEquipo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabelImagenPc = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableEquipos = new javax.swing.JTable();
        jButtonNuevoEquipo = new javax.swing.JButton();
        jButtonModificarEquipo = new javax.swing.JButton();
        jButtonEliminarEquipo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanelDatosCliente = new javax.swing.JPanel();
        jButtonBuscarCliente = new javax.swing.JButton();
        jLabelIdCliente = new javax.swing.JLabel();
        jTextFieldIdCliente = new javax.swing.JTextField();
        jLabelNombreCliente = new javax.swing.JLabel();
        jLabelApellidoCliente = new javax.swing.JLabel();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        jTextFieldApellidoCliente = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabelImagenCliente = new javax.swing.JLabel();

        jPanelDatosEquipo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del equipo"));

        jButtonAceptarEquipo.setText("Aceptar");
        jButtonAceptarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarEquipoActionPerformed(evt);
            }
        });

        jButtonCancelarEquipo.setText("Cancelar");
        jButtonCancelarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarEquipoActionPerformed(evt);
            }
        });

        jLabelIdEquipo.setText("Id Equipo:");

        jTextFieldIdEquipo.setEditable(false);

        jLabelMarcaEquipo.setText("Marca:");

        jLabelAnioEquipo.setText("Año:");

        jLabelImagenPc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/monitor.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImagenPc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImagenPc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelDatosEquipoLayout = new javax.swing.GroupLayout(jPanelDatosEquipo);
        jPanelDatosEquipo.setLayout(jPanelDatosEquipoLayout);
        jPanelDatosEquipoLayout.setHorizontalGroup(
            jPanelDatosEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosEquipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAceptarEquipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelarEquipo)
                .addContainerGap())
            .addGroup(jPanelDatosEquipoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelDatosEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelIdEquipo)
                    .addComponent(jLabelMarcaEquipo)
                    .addComponent(jLabelAnioEquipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldMarcaEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIdEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAnioEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosEquipoLayout.setVerticalGroup(
            jPanelDatosEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosEquipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDatosEquipoLayout.createSequentialGroup()
                        .addGroup(jPanelDatosEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelIdEquipo)
                            .addComponent(jTextFieldIdEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMarcaEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMarcaEquipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAnioEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAnioEquipo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanelDatosEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptarEquipo)
                    .addComponent(jButtonCancelarEquipo))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Lista de equipos"));

        jTableEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableEquipos);

        jButtonNuevoEquipo.setText("Nuevo");
        jButtonNuevoEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoEquipoActionPerformed(evt);
            }
        });

        jButtonModificarEquipo.setText("Modificar");
        jButtonModificarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarEquipoActionPerformed(evt);
            }
        });

        jButtonEliminarEquipo.setText("Eliminar");
        jButtonEliminarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarEquipoActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonNuevoEquipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModificarEquipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEliminarEquipo))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevoEquipo)
                    .addComponent(jButtonModificarEquipo)
                    .addComponent(jButtonEliminarEquipo))
                .addContainerGap())
        );

        jPanelDatosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del cliente"));

        jButtonBuscarCliente.setText("Buscar");
        jButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClienteActionPerformed(evt);
            }
        });

        jLabelIdCliente.setText("Id Cliente:");

        jLabelNombreCliente.setText("Nombre:");

        jLabelApellidoCliente.setText("Apellido:");

        jTextFieldNombreCliente.setEditable(false);

        jTextFieldApellidoCliente.setEditable(false);

        jLabelImagenCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelImagenCliente)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImagenCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelDatosClienteLayout = new javax.swing.GroupLayout(jPanelDatosCliente);
        jPanelDatosCliente.setLayout(jPanelDatosClienteLayout);
        jPanelDatosClienteLayout.setHorizontalGroup(
            jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                        .addComponent(jLabelIdCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscarCliente))
                    .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                        .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelApellidoCliente)
                            .addComponent(jLabelNombreCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldApellidoCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosClienteLayout.setVerticalGroup(
            jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdCliente)
                    .addComponent(jTextFieldIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarCliente))
                .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombreCliente)
                            .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelApellidoCliente)
                            .addComponent(jTextFieldApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDatosEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelDatosEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarEquipoActionPerformed
        // TODO add your handling code here:
        this.limpiarDatos();
        this.activarDatosCliente(false);
        this.activarDatosEquipo(false);
    }//GEN-LAST:event_jButtonCancelarEquipoActionPerformed

    private void jButtonAceptarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarEquipoActionPerformed
        // TODO add your handling code here:
        if(this.banderaModificar == -1){
            this.crearEquipo();
        }
        else{
            this.modificarEquipo();
        }
        this.activarDatosCliente(false);
        this.activarDatosEquipo(false);
        this.limpiarDatos();
        try {       
            this.actualizarFilas();
        } catch (PreexistingEntityException ex) {
            Logger.getLogger(VentanaArticulo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAceptarEquipoActionPerformed

    private void jButtonNuevoEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoEquipoActionPerformed
        // TODO add your handling code here:
        this.activarDatosCliente(true);
        this.jButtonCancelarEquipo.setEnabled(true);
    }//GEN-LAST:event_jButtonNuevoEquipoActionPerformed

    private void jButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarClienteActionPerformed
        // TODO add your handling code here:
        if(this.jTextFieldIdCliente.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "INGRESE UN CODIGO PARA REALIZAR LA BUSQUEDA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);JOptionPane.showMessageDialog(null, "INGRESE UN CODIGO PARA REALIZAR LA BUSQUEDA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
         else{
             List<Cliente> clientes = null;
            int idCliente = Integer.parseInt(this.jTextFieldIdCliente.getText());// leo y guardo el id de un cliente
            try {
                clientes = this.miLogica.dameClientes();
            } catch (PreexistingEntityException ex) {
                Logger.getLogger(VentanaTurno.class.getName()).log(Level.SEVERE, null, ex);
            }
            for(Cliente e : clientes){// recorro la lista de clientes
                if(e.isId(idCliente)){// si corresponde al id lo almaceno en unCliente
                    this.unCliente = e;
                }
            }
            if(this.unCliente != null){// verifico si encontro al cliente
                this.jTextFieldNombreCliente.setText(this.unCliente.getNombre());// muestro el nombre del cliente
                this.jTextFieldApellidoCliente.setText(this.unCliente.getApellido());// muestro el apellido del cliente
                this.activarDatosCliente(false);
                this.activarDatosEquipo(true);
            }
            else{// si no encuentro a un cliente con el idCliente
                JOptionPane.showMessageDialog(null, "NO EXISTE UN CLIENTE CON EL ID: "+idCliente, "ERROR", JOptionPane.ERROR_MESSAGE);
            }
         }
    }//GEN-LAST:event_jButtonBuscarClienteActionPerformed

    private void jButtonModificarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarEquipoActionPerformed
        // TODO add your handling code here:
        int seleccionEquipo = this.jTableEquipos.getSelectedRow();
        int i = 1;
        if(seleccionEquipo == -1){// si no se selecciono nada de la tabla
            JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE UNA FILA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        else{
            i = JOptionPane.showConfirmDialog(this, "Estas Seguro ?", "Vas a Modificar un Equipo", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                int idEquipo = Integer.parseInt(this.jTableEquipos.getValueAt(seleccionEquipo, 0).toString());
                int idCliente = Integer.parseInt(this.jTableEquipos.getValueAt(seleccionEquipo, 2).toString());
                try {
                    Cliente unCliente = this.miLogica.dameMiCliente(idCliente);
                    for(Equipo e : unCliente.getEquipos()){// recorro la lista de equipos de un cliente
                        if(e.isId(idEquipo)){
                            // datos del cliente
                            this.jTextFieldIdCliente.setText(String.valueOf(unCliente.getId()));
                            this.jTextFieldNombreCliente.setText(unCliente.getNombre());
                            this.jTextFieldApellidoCliente.setText(unCliente.getApellido());
                            // datos del equipo
                            this.jTextFieldIdEquipo.setText(String.valueOf(e.getId()));
                            this.jTextFieldMarcaEquipo.setText(e.getMarca());
                            this.jTextFieldAnioEquipo.setText(e.getAnio());
                            // activacion de datos
                            this.activarDatosCliente(false);
                            this.activarDatosEquipo(true);
                            this.banderaModificar = e.getId();// toma un numero mayor a cero
                        }
                    }
                } catch (PreexistingEntityException ex) {
                    Logger.getLogger(VentanaEquipo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButtonModificarEquipoActionPerformed

    private void jButtonEliminarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarEquipoActionPerformed
        // TODO add your handling code here:
        int seleccionEquipo = this.jTableEquipos.getSelectedRow();
        int i = 1;
        if(seleccionEquipo == -1){// si no se selecciono nada de la tabla
            JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE UNA FILA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        else{
            i = JOptionPane.showConfirmDialog(this, "Estas Seguro ?", "Vas a Modificar un Cliente", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                int idEquipo = Integer.parseInt(this.jTableEquipos.getValueAt(seleccionEquipo, 0).toString());
                int idCliente = Integer.parseInt(this.jTableEquipos.getValueAt(seleccionEquipo, 2).toString());
                try {
                    this.miLogica.eliminarEquipo(idEquipo, idCliente);
                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(VentanaEquipo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(VentanaEquipo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButtonEliminarEquipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptarEquipo;
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JButton jButtonCancelarEquipo;
    private javax.swing.JButton jButtonEliminarEquipo;
    private javax.swing.JButton jButtonModificarEquipo;
    private javax.swing.JButton jButtonNuevoEquipo;
    private javax.swing.JLabel jLabelAnioEquipo;
    private javax.swing.JLabel jLabelApellidoCliente;
    private javax.swing.JLabel jLabelIdCliente;
    private javax.swing.JLabel jLabelIdEquipo;
    private javax.swing.JLabel jLabelImagenCliente;
    private javax.swing.JLabel jLabelImagenPc;
    private javax.swing.JLabel jLabelMarcaEquipo;
    private javax.swing.JLabel jLabelNombreCliente;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelDatosCliente;
    private javax.swing.JPanel jPanelDatosEquipo;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableEquipos;
    private javax.swing.JTextField jTextFieldAnioEquipo;
    private javax.swing.JTextField jTextFieldApellidoCliente;
    private javax.swing.JTextField jTextFieldIdCliente;
    private javax.swing.JTextField jTextFieldIdEquipo;
    private javax.swing.JTextField jTextFieldMarcaEquipo;
    private javax.swing.JTextField jTextFieldNombreCliente;
    // End of variables declaration//GEN-END:variables

    public void activarDatosCliente(boolean b){
        this.jPanelDatosCliente.setEnabled(b);
        this.jLabelIdCliente.setEnabled(b);
        this.jTextFieldIdCliente.setEnabled(b);
        this.jButtonBuscarCliente.setEnabled(b);
        this.jLabelNombreCliente.setEnabled(b);
        this.jTextFieldNombreCliente.setEnabled(b);
        this.jLabelApellidoCliente.setEnabled(b);
        this.jTextFieldApellidoCliente.setEnabled(b);
        this.jLabelImagenCliente.setEnabled(b);
    }
    
    public void activarDatosEquipo(boolean b){
        this.jPanelDatosEquipo.setEnabled(b);
        this.jLabelIdEquipo.setEnabled(b);
        this.jTextFieldIdEquipo.setEnabled(b);
        this.jLabelMarcaEquipo.setEnabled(b);
        this.jTextFieldMarcaEquipo.setEnabled(b);
        this.jLabelAnioEquipo.setEnabled(b);
        this.jTextFieldAnioEquipo.setEnabled(b);
        this.jLabelImagenPc.setEnabled(b);
        this.jButtonAceptarEquipo.setEnabled(b);
        this.jButtonCancelarEquipo.setEnabled(b);
    }
    
    public void limpiarDatos(){
        this.jTextFieldIdCliente.setText("");
        this.jTextFieldNombreCliente.setText("");
        this.jTextFieldApellidoCliente.setText("");
        this.jTextFieldIdEquipo.setText("");
        this.jTextFieldMarcaEquipo.setText("");
        this.jTextFieldAnioEquipo.setText("");
        // limpiar variables locales
        this.unCliente = null;
    }
    
    public void cargarTabla() throws PreexistingEntityException{
        List<Equipo> equipos = this.miLogica.dameEquipos();
        List<Cliente> clientes = this.miLogica.dameClientes();
        Object[]fila= new Object[5];
        for(Cliente e : clientes){
                for(Equipo eq : e.getEquipos()){
                    fila[0] = eq.getId();
                    fila[1] = eq.getMarca();
                    fila[2] = e.getId();
                    fila[3] = e.getNombre();
                    fila[4] = e.getApellido();
                    this.modeloEquipo.addRow(fila);
                    this.jTableEquipos.setModel(modeloEquipo);
                }
            }
    }
    
    public void actualizarFilas() throws PreexistingEntityException{
        DefaultTableModel modelo = (DefaultTableModel) jTableEquipos.getModel();
        int filas = jTableEquipos.getRowCount();
        for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
        }
        cargarTabla();
    }
    
    public void crearEquipo(){
        String marcaEquipo = this.jTextFieldMarcaEquipo.getText();
        String anioEquipo = this.jTextFieldAnioEquipo.getText();
        try {
            this.miLogica.crearEquipo(this.unCliente.getId(), marcaEquipo, anioEquipo);
        } catch (Exception ex) {
            Logger.getLogger(VentanaEquipo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void modificarEquipo(){
        int idEquipo = Integer.parseInt(this.jTextFieldIdEquipo.getText());
        int idCliente = Integer.parseInt(this.jTextFieldIdCliente.getText());
        String marcaEquipo = this.jTextFieldMarcaEquipo.getText();
        String anioEquipo = this.jTextFieldAnioEquipo.getText();
        try {
            this.miLogica.modificarEquipo(idEquipo, idCliente, marcaEquipo, anioEquipo);
            this.banderaModificar = -1;
        } catch (Exception ex) {
            Logger.getLogger(VentanaEquipo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}
