/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logicaDeNegocio.Empleado;
import persistenciaJPA.exceptions.NonexistentEntityException;
import persistenciaJPA.exceptions.PreexistingEntityException;

/**
 *
 * @author Choni
 */
public class VentanaEmpleado extends javax.swing.JInternalFrame {
    //CONTROLADORA DE LA INTERFAZ
    private ControladoraInterfaz miLogica;
    private DefaultTableModel modeloEmpleados = new DefaultTableModel(){
        // sobreescribo el metodo para que no se modifiquen los campos de las filas en la tabla
        @Override
        public boolean isCellEditable(int rowIndex, int colIndex){
            return false;
        }
    };
    private List<Empleado> empleados = null;// lista de empleados
    private int banderaModificar;//bandera de modificacion
    /**
     * Creates new form VentanaEmpleado
     */
    public VentanaEmpleado(ControladoraInterfaz unaControladora) throws PreexistingEntityException {
        initComponents();
        this.miLogica = unaControladora;
        this.setClosable(true);// boton para cerrar
        this.setIconifiable(true);// boton para minimizar
        this.activarDatosEmpleado(false);
        // datos de busqueda
        this.jLabelTipoEmpleadoBuscar.setEnabled(false);
        this.jComboBoxTipoEmpleadoBuscar.setEnabled(false);
        this.jButtonBuscar.setEnabled(false);
        /// Agregar las cabeceras de la tabla
        this.modeloEmpleados.addColumn("Id");
        this.modeloEmpleados.addColumn("Nombre");
        this.modeloEmpleados.addColumn("Apellido");
        this.modeloEmpleados.addColumn("Telefono");
        this.modeloEmpleados.addColumn("Tipo de Empleado");
        this.modeloEmpleados.addColumn("Salario");
        this.jTableEmpleado.setModel(this.modeloEmpleados);
        
        this.cargarTabla();
        banderaModificar = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelId = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelCorreoElectronico = new javax.swing.JLabel();
        jLabelDomicilio = new javax.swing.JLabel();
        jLabelDni = new javax.swing.JLabel();
        jLabelCuil = new javax.swing.JLabel();
        jLabelTipoEmpleado = new javax.swing.JLabel();
        jLabelSalarioMensual = new javax.swing.JLabel();
        jComboBoxTipoDeEmpleado = new javax.swing.JComboBox();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldCorreoElectronico = new javax.swing.JTextField();
        jTextFieldDomicilio = new javax.swing.JTextField();
        jTextFieldDni = new javax.swing.JTextField();
        jTextFieldCuil = new javax.swing.JTextField();
        jTextFieldSalarioMensual = new javax.swing.JTextField();
        jCheckBoxTelefono = new javax.swing.JCheckBox();
        jCheckBoxCorreoElectronico = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jButtonNuevo = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelTipoEmpleadoBuscar = new javax.swing.JLabel();
        jComboBoxTipoEmpleadoBuscar = new javax.swing.JComboBox();
        jButtonBuscar = new javax.swing.JButton();
        jCheckBoxBuscarEmpleado = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEmpleado = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del empleado"));

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelId.setText("Id:");

        jLabelNombre.setText("Nombre:");

        jLabelApellido.setText("Apellido:");

        jLabelTelefono.setText("Telefono:");

        jLabelCorreoElectronico.setText("Correo electronico:");

        jLabelDomicilio.setText("Domicilio:");

        jLabelDni.setText("DNI:");

        jLabelCuil.setText("CUIL:");

        jLabelTipoEmpleado.setText("Tipo de empleado:");

        jLabelSalarioMensual.setText("Salario mensual: $");

        jComboBoxTipoDeEmpleado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldId.setEditable(false);

        jCheckBoxTelefono.setText("S/N");
        jCheckBoxTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTelefonoActionPerformed(evt);
            }
        });

        jCheckBoxCorreoElectronico.setText("S/N");
        jCheckBoxCorreoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCorreoElectronicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabelTelefono))
                            .addComponent(jLabelCorreoElectronico, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxCorreoElectronico))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxTelefono))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabelApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelSalarioMensual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSalarioMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDomicilio)
                            .addComponent(jLabelTipoEmpleado)
                            .addComponent(jLabelDni)
                            .addComponent(jLabelCuil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTipoDeEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCuil, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefono)
                    .addComponent(jCheckBoxTelefono))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCorreoElectronico)
                    .addComponent(jTextFieldCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxCorreoElectronico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDomicilio)
                    .addComponent(jTextFieldDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDni)
                    .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCuil)
                    .addComponent(jTextFieldCuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoEmpleado)
                    .addComponent(jComboBoxTipoDeEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalarioMensual)
                    .addComponent(jTextFieldSalarioMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Empleados"));

        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTipoEmpleadoBuscar.setText("Tipo de empleado:");

        jComboBoxTipoEmpleadoBuscar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonBuscar.setText("Buscar");

        jCheckBoxBuscarEmpleado.setText("Buscar empleado");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelTipoEmpleadoBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTipoEmpleadoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButtonBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(jCheckBoxBuscarEmpleado)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoEmpleadoBuscar)
                    .addComponent(jComboBoxTipoEmpleadoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jCheckBoxBuscarEmpleado))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTableEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableEmpleado);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEliminar))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevo)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonEliminar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        int seleccionEmpleado = this.jTableEmpleado.getSelectedRow();
        int i = 1;
        if(seleccionEmpleado == -1){// si no se selecciono nada de la tabla
            JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE UNA FILA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        else{
            i = JOptionPane.showConfirmDialog(this, "Estas Seguro ?", "Vas a Modificar un Empleado", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                int id = Integer.parseInt(this.jTableEmpleado.getValueAt(seleccionEmpleado, 0).toString());
                try {
                    this.miLogica.eliminarEmpleado(id);
                    DefaultTableModel dtm = (DefaultTableModel) jTableEmpleado.getModel();
                    dtm.removeRow(jTableEmpleado.getSelectedRow());                    
                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(VentanaCliente.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(VentanaCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        // TODO add your handling code here:
        this.activarDatosEmpleado(true);
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jCheckBoxTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTelefonoActionPerformed
        // TODO add your handling code here:
        if (this.jCheckBoxTelefono.isSelected()) {
            this.jTextFieldTelefono.setText("Sin Telefono");
            this.jTextFieldTelefono.setEnabled(false);
        } else {
            this.jTextFieldTelefono.setEnabled(true);
            this.jTextFieldTelefono.setText("");
        }
    }//GEN-LAST:event_jCheckBoxTelefonoActionPerformed

    private void jCheckBoxCorreoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCorreoElectronicoActionPerformed
        // TODO add your handling code here:
        if (this.jCheckBoxCorreoElectronico.isSelected()) {
            this.jTextFieldCorreoElectronico.setText("Sin Correo Electronico");
            this.jTextFieldCorreoElectronico.setEnabled(false);
        } else {
            this.jTextFieldCorreoElectronico.setEnabled(true);
            this.jTextFieldCorreoElectronico.setText("");
        }
    }//GEN-LAST:event_jCheckBoxCorreoElectronicoActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        if(this.banderaModificar == -1){
            this.crearEmpleado();
        }
        else{
            this.modificarEmpleado();
        }
        this.activarDatosEmpleado(false);
        this.limpiarDatosEmpleado();
        try {       
            actualizarFilas();
        } catch (PreexistingEntityException ex) {
            Logger.getLogger(VentanaArticulo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.activarDatosEmpleado(false);
        this.limpiarDatosEmpleado();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        int seleccionArticulo = this.jTableEmpleado.getSelectedRow();
        int i = 1;
        if(seleccionArticulo == -1){// si no se selecciono nada de la tabla
            JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE UNA FILA", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        else{
            i = JOptionPane.showConfirmDialog(this, "Estas Seguro ?", "Vas a Modificar un Empleado", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                int id = Integer.parseInt(this.jTableEmpleado.getValueAt(seleccionArticulo, 0).toString());
                try {
                    Empleado unEmpleado = miLogica.dameMiEmpleado(id);
                    this.activarDatosEmpleado(true);
                    this.jTextFieldNombre.setText(unEmpleado.getNombre());
                    this.jTextFieldApellido.setText(unEmpleado.getApellido());
                    if(unEmpleado.getTelefono().equalsIgnoreCase("Sin Telefono")){
                        this.jTextFieldTelefono.setText("Sin Telefono");
                        this.jCheckBoxTelefono.setSelected(true);
                        this.jTextFieldTelefono.setEnabled(false);
                    }
                    else{
                        this.jTextFieldTelefono.setText(unEmpleado.getTelefono());
                        this.jCheckBoxTelefono.setSelected(false);
                    }  
                    if(unEmpleado.getCorreoElectronico().equalsIgnoreCase("Sin Correo Electronico")){
                        this.jTextFieldCorreoElectronico.setText("Sin Correo Electronico");
                        this.jCheckBoxCorreoElectronico.setSelected(true);
                        this.jTextFieldCorreoElectronico.setEnabled(false);
                    }
                    else{
                        this.jTextFieldCorreoElectronico.setText(unEmpleado.getCorreoElectronico());
                        this.jCheckBoxCorreoElectronico.setSelected(false);
                    }        
                    this.jTextFieldDomicilio.setText(unEmpleado.getDomicilio());
                    this.jTextFieldDni.setText(unEmpleado.getDni());
                    this.jTextFieldCuil.setText(unEmpleado.getCuil());
                    this.jTextFieldId.setText(String.valueOf(unEmpleado.getId()));
                    this.banderaModificar = unEmpleado.getId();
                    if(unEmpleado.getTipoEmpleado().equalsIgnoreCase("Item 1")){
                        this.jComboBoxTipoDeEmpleado.setSelectedIndex(0);
                    }
                    this.jTextFieldSalarioMensual.setText(String.valueOf(unEmpleado.getSalario()));
                } catch (PreexistingEntityException ex) {
                    Logger.getLogger(VentanaProveedor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JCheckBox jCheckBoxBuscarEmpleado;
    private javax.swing.JCheckBox jCheckBoxCorreoElectronico;
    private javax.swing.JCheckBox jCheckBoxTelefono;
    private javax.swing.JComboBox jComboBoxTipoDeEmpleado;
    private javax.swing.JComboBox jComboBoxTipoEmpleadoBuscar;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCorreoElectronico;
    private javax.swing.JLabel jLabelCuil;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelDomicilio;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSalarioMensual;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTipoEmpleado;
    private javax.swing.JLabel jLabelTipoEmpleadoBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableEmpleado;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCorreoElectronico;
    private javax.swing.JTextField jTextFieldCuil;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldDomicilio;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldSalarioMensual;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables

    public void activarDatosEmpleado(boolean b){
        this.jLabelId.setEnabled(b);
        this.jLabelNombre.setEnabled(b);
        this.jLabelApellido.setEnabled(b);
        this.jLabelTelefono.setEnabled(b);
        this.jLabelCorreoElectronico.setEnabled(b);
        this.jLabelDomicilio.setEnabled(b);
        this.jLabelDni.setEnabled(b);
        this.jLabelCuil.setEnabled(b);
        this.jLabelSalarioMensual.setEnabled(b);
        this.jLabelTipoEmpleado.setEnabled(b);
        this.jCheckBoxTelefono.setEnabled(b);
        this.jCheckBoxCorreoElectronico.setEnabled(b);
        this.jComboBoxTipoDeEmpleado.setEnabled(b);
        this.jButtonCancelar.setEnabled(b);
        this.jButtonAceptar.setEnabled(b);
        this.jTextFieldSalarioMensual.setEnabled(b);
        this.jTextFieldNombre.setEnabled(b);
        this.jTextFieldApellido.setEnabled(b);
        this.jTextFieldTelefono.setEnabled(b);
        this.jTextFieldCorreoElectronico.setEnabled(b);
        this.jTextFieldDomicilio.setEnabled(b);
        this.jTextFieldDni.setEnabled(b);
        this.jTextFieldCuil.setEnabled(b);        
    }

    public void cargarTabla() throws PreexistingEntityException{
        List<Empleado> empleados = this.miLogica.dameEmpleados();
        Object[]fila= new Object[9];
        for(Empleado e : empleados){
            fila[0] = e.getId();
            fila[1] = e.getNombre();
            fila[2] = e.getApellido();
            fila[3] = e.getTelefono();
            fila[4] = e.getTipoEmpleado();
            fila[5] = e.getSalario();
            this.modeloEmpleados.addRow(fila);
            this.jTableEmpleado.setModel(modeloEmpleados);
        }        
    }
    
    public void crearEmpleado(){
        String nombre = this.jTextFieldNombre.getText();
        String apellido = this.jTextFieldApellido.getText();
        String telefono = this.jTextFieldTelefono.getText();
        String correoElectronico = this.jTextFieldCorreoElectronico.getText();
        String domicilio = this.jTextFieldDomicilio.getText();
        String dni = this.jTextFieldDni.getText();
        String cuil = this.jTextFieldCuil.getText();
        String tipoEmpleado = this.jComboBoxTipoDeEmpleado.getSelectedItem().toString();
        float salarioMensual = Float.valueOf(this.jTextFieldSalarioMensual.getText());
        try {        
            this.miLogica.crearEmpleado(nombre, apellido, telefono, correoElectronico, domicilio, dni, cuil, tipoEmpleado, salarioMensual);
        } catch (Exception ex) {
            Logger.getLogger(VentanaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void limpiarDatosEmpleado(){
        this.jTextFieldNombre.setText("");
        this.jTextFieldApellido.setText("");
        this.jTextFieldTelefono.setText("");
        this.jTextFieldCorreoElectronico.setText("");
        this.jTextFieldDomicilio.setText("");
        this.jTextFieldDni.setText("");
        this.jTextFieldCuil.setText("");
        this.jTextFieldId.setText("");
        this.jCheckBoxCorreoElectronico.setSelected(false);
        this.jCheckBoxTelefono.setSelected(false);
        this.jComboBoxTipoDeEmpleado.setSelectedIndex(0);
        this.jTextFieldSalarioMensual.setText("");
    }
    
    public void actualizarFilas() throws PreexistingEntityException{
        DefaultTableModel modelo = (DefaultTableModel) jTableEmpleado.getModel();
        int filas = jTableEmpleado.getRowCount();
        for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
        }
        cargarTabla();
    }
    
    public void modificarEmpleado(){
        String nombre = this.jTextFieldNombre.getText();
        String apellido = this.jTextFieldApellido.getText();
        String telefono = this.jTextFieldTelefono.getText();
        String correoElectronico = this.jTextFieldCorreoElectronico.getText();
        String domicilio = this.jTextFieldDomicilio.getText();
        String dni = this.jTextFieldDni.getText();
        String cuil = this.jTextFieldCuil.getText();
        boolean condicionCliente;
        String tipoEmpleado = this.jComboBoxTipoDeEmpleado.getSelectedItem().toString();
        int id = Integer.parseInt(this.jTextFieldId.getText()); 
        float salarioMensual = Float.valueOf(this.jTextFieldSalarioMensual.getText());
        try {
            this.miLogica.modificarEmpleado(id, nombre, apellido, telefono, correoElectronico, domicilio, dni, cuil, tipoEmpleado, salarioMensual);
            this.banderaModificar = -1;
        } catch (Exception ex) {
            Logger.getLogger(VentanaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
